package com.talkweb.ei.outmanager.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

import com.talkweb.ei.outmanager.model.OutUserExample.Criteria;

public class OutContractExample  extends ExampleObj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    public OutContractExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andConTypeIsNull() {
            addCriterion("CON_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andConTypeIsNotNull() {
            addCriterion("CON_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andConTypeEqualTo(String value) {
            addCriterion("CON_TYPE =", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeNotEqualTo(String value) {
            addCriterion("CON_TYPE <>", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeGreaterThan(String value) {
            addCriterion("CON_TYPE >", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CON_TYPE >=", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeLessThan(String value) {
            addCriterion("CON_TYPE <", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeLessThanOrEqualTo(String value) {
            addCriterion("CON_TYPE <=", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeLike(String value) {
            addCriterion("CON_TYPE like", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeNotLike(String value) {
            addCriterion("CON_TYPE not like", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeIn(List<String> values) {
            addCriterion("CON_TYPE in", values, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeNotIn(List<String> values) {
            addCriterion("CON_TYPE not in", values, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeBetween(String value1, String value2) {
            addCriterion("CON_TYPE between", value1, value2, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeNotBetween(String value1, String value2) {
            addCriterion("CON_TYPE not between", value1, value2, "conType");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("UNIT is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("UNIT =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("UNIT <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("UNIT >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("UNIT >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("UNIT <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("UNIT <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("UNIT like", value, "unit");
            return (Criteria) this;
        }
        
        
        //特殊的单位处理，格式如下：/xxxx/xxxxx/
        public Criteria andUnitRECLike(String value) {
            addCriterion(" '"+value+"' like '%/'||UNIT||'/%'");
            return (Criteria) this;
        }  

        public Criteria andUnitNotLike(String value) {
            addCriterion("UNIT not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("UNIT in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("UNIT not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("UNIT between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("UNIT not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andCompanyidIsNull() {
            addCriterion("COMPANYID is null");
            return (Criteria) this;
        }

        public Criteria andCompanyidIsNotNull() {
            addCriterion("COMPANYID is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyidEqualTo(String value) {
            addCriterion("COMPANYID =", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidNotEqualTo(String value) {
            addCriterion("COMPANYID <>", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidGreaterThan(String value) {
            addCriterion("COMPANYID >", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANYID >=", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidLessThan(String value) {
            addCriterion("COMPANYID <", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidLessThanOrEqualTo(String value) {
            addCriterion("COMPANYID <=", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidLike(String value) {
            addCriterion("COMPANYID like", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidNotLike(String value) {
            addCriterion("COMPANYID not like", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidIn(List<String> values) {
            addCriterion("COMPANYID in", values, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidNotIn(List<String> values) {
            addCriterion("COMPANYID not in", values, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidBetween(String value1, String value2) {
            addCriterion("COMPANYID between", value1, value2, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidNotBetween(String value1, String value2) {
            addCriterion("COMPANYID not between", value1, value2, "companyid");
            return (Criteria) this;
        }

        public Criteria andJineIsNull() {
            addCriterion("JINE is null");
            return (Criteria) this;
        }

        public Criteria andJineIsNotNull() {
            addCriterion("JINE is not null");
            return (Criteria) this;
        }

        public Criteria andJineEqualTo(String value) {
            addCriterion("JINE =", value, "jine");
            return (Criteria) this;
        }

        public Criteria andJineNotEqualTo(String value) {
            addCriterion("JINE <>", value, "jine");
            return (Criteria) this;
        }

        public Criteria andJineGreaterThan(String value) {
            addCriterion("JINE >", value, "jine");
            return (Criteria) this;
        }

        public Criteria andJineGreaterThanOrEqualTo(String value) {
            addCriterion("JINE >=", value, "jine");
            return (Criteria) this;
        }

        public Criteria andJineLessThan(String value) {
            addCriterion("JINE <", value, "jine");
            return (Criteria) this;
        }

        public Criteria andJineLessThanOrEqualTo(String value) {
            addCriterion("JINE <=", value, "jine");
            return (Criteria) this;
        }

        public Criteria andJineLike(String value) {
            addCriterion("JINE like", value, "jine");
            return (Criteria) this;
        }

        public Criteria andJineNotLike(String value) {
            addCriterion("JINE not like", value, "jine");
            return (Criteria) this;
        }

        public Criteria andJineIn(List<String> values) {
            addCriterion("JINE in", values, "jine");
            return (Criteria) this;
        }

        public Criteria andJineNotIn(List<String> values) {
            addCriterion("JINE not in", values, "jine");
            return (Criteria) this;
        }

        public Criteria andJineBetween(String value1, String value2) {
            addCriterion("JINE between", value1, value2, "jine");
            return (Criteria) this;
        }

        public Criteria andJineNotBetween(String value1, String value2) {
            addCriterion("JINE not between", value1, value2, "jine");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("STARTDATE is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("STARTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(Date value) {
            addCriterionForJDBCDate("STARTDATE =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("STARTDATE <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(Date value) {
            addCriterionForJDBCDate("STARTDATE >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("STARTDATE >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(Date value) {
            addCriterionForJDBCDate("STARTDATE <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("STARTDATE <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<Date> values) {
            addCriterionForJDBCDate("STARTDATE in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("STARTDATE not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("STARTDATE between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("STARTDATE not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("ENDDATE is null");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("ENDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andEnddateEqualTo(Date value) {
            addCriterionForJDBCDate("ENDDATE =", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("ENDDATE <>", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThan(Date value) {
            addCriterionForJDBCDate("ENDDATE >", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ENDDATE >=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThan(Date value) {
            addCriterionForJDBCDate("ENDDATE <", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ENDDATE <=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateIn(List<Date> values) {
            addCriterionForJDBCDate("ENDDATE in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("ENDDATE not in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ENDDATE between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ENDDATE not between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andQixianIsNull() {
            addCriterion("QIXIAN is null");
            return (Criteria) this;
        }

        public Criteria andQixianIsNotNull() {
            addCriterion("QIXIAN is not null");
            return (Criteria) this;
        }

        public Criteria andQixianEqualTo(String value) {
            addCriterion("QIXIAN =", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianNotEqualTo(String value) {
            addCriterion("QIXIAN <>", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianGreaterThan(String value) {
            addCriterion("QIXIAN >", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianGreaterThanOrEqualTo(String value) {
            addCriterion("QIXIAN >=", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianLessThan(String value) {
            addCriterion("QIXIAN <", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianLessThanOrEqualTo(String value) {
            addCriterion("QIXIAN <=", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianLike(String value) {
            addCriterion("QIXIAN like", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianNotLike(String value) {
            addCriterion("QIXIAN not like", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianIn(List<String> values) {
            addCriterion("QIXIAN in", values, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianNotIn(List<String> values) {
            addCriterion("QIXIAN not in", values, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianBetween(String value1, String value2) {
            addCriterion("QIXIAN between", value1, value2, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianNotBetween(String value1, String value2) {
            addCriterion("QIXIAN not between", value1, value2, "qixian");
            return (Criteria) this;
        }

        public Criteria andYewuIsNull() {
            addCriterion("YEWU is null");
            return (Criteria) this;
        }

        public Criteria andYewuIsNotNull() {
            addCriterion("YEWU is not null");
            return (Criteria) this;
        }

        public Criteria andYewuEqualTo(String value) {
            addCriterion("YEWU =", value, "yewu");
            return (Criteria) this;
        }

        public Criteria andYewuNotEqualTo(String value) {
            addCriterion("YEWU <>", value, "yewu");
            return (Criteria) this;
        }

        public Criteria andYewuGreaterThan(String value) {
            addCriterion("YEWU >", value, "yewu");
            return (Criteria) this;
        }

        public Criteria andYewuGreaterThanOrEqualTo(String value) {
            addCriterion("YEWU >=", value, "yewu");
            return (Criteria) this;
        }

        public Criteria andYewuLessThan(String value) {
            addCriterion("YEWU <", value, "yewu");
            return (Criteria) this;
        }

        public Criteria andYewuLessThanOrEqualTo(String value) {
            addCriterion("YEWU <=", value, "yewu");
            return (Criteria) this;
        }

        public Criteria andYewuLike(String value) {
            addCriterion("YEWU like", value, "yewu");
            return (Criteria) this;
        }

        public Criteria andYewuNotLike(String value) {
            addCriterion("YEWU not like", value, "yewu");
            return (Criteria) this;
        }

        public Criteria andYewuIn(List<String> values) {
            addCriterion("YEWU in", values, "yewu");
            return (Criteria) this;
        }

        public Criteria andYewuNotIn(List<String> values) {
            addCriterion("YEWU not in", values, "yewu");
            return (Criteria) this;
        }

        public Criteria andYewuBetween(String value1, String value2) {
            addCriterion("YEWU between", value1, value2, "yewu");
            return (Criteria) this;
        }

        public Criteria andYewuNotBetween(String value1, String value2) {
            addCriterion("YEWU not between", value1, value2, "yewu");
            return (Criteria) this;
        }

        public Criteria andAttsIsNull() {
            addCriterion("ATTS is null");
            return (Criteria) this;
        }

        public Criteria andAttsIsNotNull() {
            addCriterion("ATTS is not null");
            return (Criteria) this;
        }

        public Criteria andAttsEqualTo(String value) {
            addCriterion("ATTS =", value, "atts");
            return (Criteria) this;
        }

        public Criteria andAttsNotEqualTo(String value) {
            addCriterion("ATTS <>", value, "atts");
            return (Criteria) this;
        }

        public Criteria andAttsGreaterThan(String value) {
            addCriterion("ATTS >", value, "atts");
            return (Criteria) this;
        }

        public Criteria andAttsGreaterThanOrEqualTo(String value) {
            addCriterion("ATTS >=", value, "atts");
            return (Criteria) this;
        }

        public Criteria andAttsLessThan(String value) {
            addCriterion("ATTS <", value, "atts");
            return (Criteria) this;
        }

        public Criteria andAttsLessThanOrEqualTo(String value) {
            addCriterion("ATTS <=", value, "atts");
            return (Criteria) this;
        }

        public Criteria andAttsLike(String value) {
            addCriterion("ATTS like", value, "atts");
            return (Criteria) this;
        }

        public Criteria andAttsNotLike(String value) {
            addCriterion("ATTS not like", value, "atts");
            return (Criteria) this;
        }

        public Criteria andAttsIn(List<String> values) {
            addCriterion("ATTS in", values, "atts");
            return (Criteria) this;
        }

        public Criteria andAttsNotIn(List<String> values) {
            addCriterion("ATTS not in", values, "atts");
            return (Criteria) this;
        }

        public Criteria andAttsBetween(String value1, String value2) {
            addCriterion("ATTS between", value1, value2, "atts");
            return (Criteria) this;
        }

        public Criteria andAttsNotBetween(String value1, String value2) {
            addCriterion("ATTS not between", value1, value2, "atts");
            return (Criteria) this;
        }

        public Criteria andBuchongIsNull() {
            addCriterion("BUCHONG is null");
            return (Criteria) this;
        }

        public Criteria andBuchongIsNotNull() {
            addCriterion("BUCHONG is not null");
            return (Criteria) this;
        }

        public Criteria andBuchongEqualTo(String value) {
            addCriterion("BUCHONG =", value, "buchong");
            return (Criteria) this;
        }

        public Criteria andBuchongNotEqualTo(String value) {
            addCriterion("BUCHONG <>", value, "buchong");
            return (Criteria) this;
        }

        public Criteria andBuchongGreaterThan(String value) {
            addCriterion("BUCHONG >", value, "buchong");
            return (Criteria) this;
        }

        public Criteria andBuchongGreaterThanOrEqualTo(String value) {
            addCriterion("BUCHONG >=", value, "buchong");
            return (Criteria) this;
        }

        public Criteria andBuchongLessThan(String value) {
            addCriterion("BUCHONG <", value, "buchong");
            return (Criteria) this;
        }

        public Criteria andBuchongLessThanOrEqualTo(String value) {
            addCriterion("BUCHONG <=", value, "buchong");
            return (Criteria) this;
        }

        public Criteria andBuchongLike(String value) {
            addCriterion("BUCHONG like", value, "buchong");
            return (Criteria) this;
        }

        public Criteria andBuchongNotLike(String value) {
            addCriterion("BUCHONG not like", value, "buchong");
            return (Criteria) this;
        }

        public Criteria andBuchongIn(List<String> values) {
            addCriterion("BUCHONG in", values, "buchong");
            return (Criteria) this;
        }

        public Criteria andBuchongNotIn(List<String> values) {
            addCriterion("BUCHONG not in", values, "buchong");
            return (Criteria) this;
        }

        public Criteria andBuchongBetween(String value1, String value2) {
            addCriterion("BUCHONG between", value1, value2, "buchong");
            return (Criteria) this;
        }

        public Criteria andBuchongNotBetween(String value1, String value2) {
            addCriterion("BUCHONG not between", value1, value2, "buchong");
            return (Criteria) this;
        }

        public Criteria andConCodeIsNull() {
            addCriterion("CON_CODE is null");
            return (Criteria) this;
        }

        public Criteria andConCodeIsNotNull() {
            addCriterion("CON_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andConCodeEqualTo(String value) {
            addCriterion("CON_CODE =", value, "conCode");
            return (Criteria) this;
        }

        public Criteria andConCodeNotEqualTo(String value) {
            addCriterion("CON_CODE <>", value, "conCode");
            return (Criteria) this;
        }

        public Criteria andConCodeGreaterThan(String value) {
            addCriterion("CON_CODE >", value, "conCode");
            return (Criteria) this;
        }

        public Criteria andConCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CON_CODE >=", value, "conCode");
            return (Criteria) this;
        }

        public Criteria andConCodeLessThan(String value) {
            addCriterion("CON_CODE <", value, "conCode");
            return (Criteria) this;
        }

        public Criteria andConCodeLessThanOrEqualTo(String value) {
            addCriterion("CON_CODE <=", value, "conCode");
            return (Criteria) this;
        }

        public Criteria andConCodeLike(String value) {
            addCriterion("CON_CODE like", value, "conCode");
            return (Criteria) this;
        }

        public Criteria andConCodeNotLike(String value) {
            addCriterion("CON_CODE not like", value, "conCode");
            return (Criteria) this;
        }

        public Criteria andConCodeIn(List<String> values) {
            addCriterion("CON_CODE in", values, "conCode");
            return (Criteria) this;
        }

        public Criteria andConCodeNotIn(List<String> values) {
            addCriterion("CON_CODE not in", values, "conCode");
            return (Criteria) this;
        }

        public Criteria andConCodeBetween(String value1, String value2) {
            addCriterion("CON_CODE between", value1, value2, "conCode");
            return (Criteria) this;
        }

        public Criteria andConCodeNotBetween(String value1, String value2) {
            addCriterion("CON_CODE not between", value1, value2, "conCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated do_not_delete_during_merge Mon May 01 15:21:12 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}