package com.talkweb.ei.outmanager.model;

import java.util.ArrayList;
import java.util.List;

public class OutCompanyExample extends ExampleObj{

	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    public OutCompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

  

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:14 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andConTypeIsNull() {
            addCriterion("CON_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andConTypeIsNotNull() {
            addCriterion("CON_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andConTypeEqualTo(String value) {
            addCriterion("CON_TYPE =", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeNotEqualTo(String value) {
            addCriterion("CON_TYPE <>", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeGreaterThan(String value) {
            addCriterion("CON_TYPE >", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeGreaterThanOrEqualTo(String value) {
            addCriterion("CON_TYPE >=", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeLessThan(String value) {
            addCriterion("CON_TYPE <", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeLessThanOrEqualTo(String value) {
            addCriterion("CON_TYPE <=", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeLike(String value) {
            addCriterion("CON_TYPE like", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeNotLike(String value) {
            addCriterion("CON_TYPE not like", value, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeIn(List<String> values) {
            addCriterion("CON_TYPE in", values, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeNotIn(List<String> values) {
            addCriterion("CON_TYPE not in", values, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeBetween(String value1, String value2) {
            addCriterion("CON_TYPE between", value1, value2, "conType");
            return (Criteria) this;
        }

        public Criteria andConTypeNotBetween(String value1, String value2) {
            addCriterion("CON_TYPE not between", value1, value2, "conType");
            return (Criteria) this;
        }

        public Criteria andBossIsNull() {
            addCriterion("BOSS is null");
            return (Criteria) this;
        }

        public Criteria andBossIsNotNull() {
            addCriterion("BOSS is not null");
            return (Criteria) this;
        }

        public Criteria andBossEqualTo(String value) {
            addCriterion("BOSS =", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossNotEqualTo(String value) {
            addCriterion("BOSS <>", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossGreaterThan(String value) {
            addCriterion("BOSS >", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossGreaterThanOrEqualTo(String value) {
            addCriterion("BOSS >=", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossLessThan(String value) {
            addCriterion("BOSS <", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossLessThanOrEqualTo(String value) {
            addCriterion("BOSS <=", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossLike(String value) {
            addCriterion("BOSS like", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossNotLike(String value) {
            addCriterion("BOSS not like", value, "boss");
            return (Criteria) this;
        }

        public Criteria andBossIn(List<String> values) {
            addCriterion("BOSS in", values, "boss");
            return (Criteria) this;
        }

        public Criteria andBossNotIn(List<String> values) {
            addCriterion("BOSS not in", values, "boss");
            return (Criteria) this;
        }

        public Criteria andBossBetween(String value1, String value2) {
            addCriterion("BOSS between", value1, value2, "boss");
            return (Criteria) this;
        }

        public Criteria andBossNotBetween(String value1, String value2) {
            addCriterion("BOSS not between", value1, value2, "boss");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andZijinIsNull() {
            addCriterion("ZIJIN is null");
            return (Criteria) this;
        }

        public Criteria andZijinIsNotNull() {
            addCriterion("ZIJIN is not null");
            return (Criteria) this;
        }

        public Criteria andZijinEqualTo(String value) {
            addCriterion("ZIJIN =", value, "zijin");
            return (Criteria) this;
        }

        public Criteria andZijinNotEqualTo(String value) {
            addCriterion("ZIJIN <>", value, "zijin");
            return (Criteria) this;
        }

        public Criteria andZijinGreaterThan(String value) {
            addCriterion("ZIJIN >", value, "zijin");
            return (Criteria) this;
        }

        public Criteria andZijinGreaterThanOrEqualTo(String value) {
            addCriterion("ZIJIN >=", value, "zijin");
            return (Criteria) this;
        }

        public Criteria andZijinLessThan(String value) {
            addCriterion("ZIJIN <", value, "zijin");
            return (Criteria) this;
        }

        public Criteria andZijinLessThanOrEqualTo(String value) {
            addCriterion("ZIJIN <=", value, "zijin");
            return (Criteria) this;
        }

        public Criteria andZijinLike(String value) {
            addCriterion("ZIJIN like", value, "zijin");
            return (Criteria) this;
        }

        public Criteria andZijinNotLike(String value) {
            addCriterion("ZIJIN not like", value, "zijin");
            return (Criteria) this;
        }

        public Criteria andZijinIn(List<String> values) {
            addCriterion("ZIJIN in", values, "zijin");
            return (Criteria) this;
        }

        public Criteria andZijinNotIn(List<String> values) {
            addCriterion("ZIJIN not in", values, "zijin");
            return (Criteria) this;
        }

        public Criteria andZijinBetween(String value1, String value2) {
            addCriterion("ZIJIN between", value1, value2, "zijin");
            return (Criteria) this;
        }

        public Criteria andZijinNotBetween(String value1, String value2) {
            addCriterion("ZIJIN not between", value1, value2, "zijin");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("AREA is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("AREA is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("AREA =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("AREA <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("AREA >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("AREA >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("AREA <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("AREA <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("AREA like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("AREA not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("AREA in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("AREA not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("AREA between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("AREA not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andZhizhaoIsNull() {
            addCriterion("ZHIZHAO is null");
            return (Criteria) this;
        }

        public Criteria andZhizhaoIsNotNull() {
            addCriterion("ZHIZHAO is not null");
            return (Criteria) this;
        }

        public Criteria andZhizhaoEqualTo(String value) {
            addCriterion("ZHIZHAO =", value, "zhizhao");
            return (Criteria) this;
        }

        public Criteria andZhizhaoNotEqualTo(String value) {
            addCriterion("ZHIZHAO <>", value, "zhizhao");
            return (Criteria) this;
        }

        public Criteria andZhizhaoGreaterThan(String value) {
            addCriterion("ZHIZHAO >", value, "zhizhao");
            return (Criteria) this;
        }

        public Criteria andZhizhaoGreaterThanOrEqualTo(String value) {
            addCriterion("ZHIZHAO >=", value, "zhizhao");
            return (Criteria) this;
        }

        public Criteria andZhizhaoLessThan(String value) {
            addCriterion("ZHIZHAO <", value, "zhizhao");
            return (Criteria) this;
        }

        public Criteria andZhizhaoLessThanOrEqualTo(String value) {
            addCriterion("ZHIZHAO <=", value, "zhizhao");
            return (Criteria) this;
        }

        public Criteria andZhizhaoLike(String value) {
            addCriterion("ZHIZHAO like", value, "zhizhao");
            return (Criteria) this;
        }

        public Criteria andZhizhaoNotLike(String value) {
            addCriterion("ZHIZHAO not like", value, "zhizhao");
            return (Criteria) this;
        }

        public Criteria andZhizhaoIn(List<String> values) {
            addCriterion("ZHIZHAO in", values, "zhizhao");
            return (Criteria) this;
        }

        public Criteria andZhizhaoNotIn(List<String> values) {
            addCriterion("ZHIZHAO not in", values, "zhizhao");
            return (Criteria) this;
        }

        public Criteria andZhizhaoBetween(String value1, String value2) {
            addCriterion("ZHIZHAO between", value1, value2, "zhizhao");
            return (Criteria) this;
        }

        public Criteria andZhizhaoNotBetween(String value1, String value2) {
            addCriterion("ZHIZHAO not between", value1, value2, "zhizhao");
            return (Criteria) this;
        }

        public Criteria andZizhidocIsNull() {
            addCriterion("ZIZHIDOC is null");
            return (Criteria) this;
        }

        public Criteria andZizhidocIsNotNull() {
            addCriterion("ZIZHIDOC is not null");
            return (Criteria) this;
        }

        public Criteria andZizhidocEqualTo(String value) {
            addCriterion("ZIZHIDOC =", value, "zizhidoc");
            return (Criteria) this;
        }

        public Criteria andZizhidocNotEqualTo(String value) {
            addCriterion("ZIZHIDOC <>", value, "zizhidoc");
            return (Criteria) this;
        }

        public Criteria andZizhidocGreaterThan(String value) {
            addCriterion("ZIZHIDOC >", value, "zizhidoc");
            return (Criteria) this;
        }

        public Criteria andZizhidocGreaterThanOrEqualTo(String value) {
            addCriterion("ZIZHIDOC >=", value, "zizhidoc");
            return (Criteria) this;
        }

        public Criteria andZizhidocLessThan(String value) {
            addCriterion("ZIZHIDOC <", value, "zizhidoc");
            return (Criteria) this;
        }

        public Criteria andZizhidocLessThanOrEqualTo(String value) {
            addCriterion("ZIZHIDOC <=", value, "zizhidoc");
            return (Criteria) this;
        }

        public Criteria andZizhidocLike(String value) {
            addCriterion("ZIZHIDOC like", value, "zizhidoc");
            return (Criteria) this;
        }

        public Criteria andZizhidocNotLike(String value) {
            addCriterion("ZIZHIDOC not like", value, "zizhidoc");
            return (Criteria) this;
        }

        public Criteria andZizhidocIn(List<String> values) {
            addCriterion("ZIZHIDOC in", values, "zizhidoc");
            return (Criteria) this;
        }

        public Criteria andZizhidocNotIn(List<String> values) {
            addCriterion("ZIZHIDOC not in", values, "zizhidoc");
            return (Criteria) this;
        }

        public Criteria andZizhidocBetween(String value1, String value2) {
            addCriterion("ZIZHIDOC between", value1, value2, "zizhidoc");
            return (Criteria) this;
        }

        public Criteria andZizhidocNotBetween(String value1, String value2) {
            addCriterion("ZIZHIDOC not between", value1, value2, "zizhidoc");
            return (Criteria) this;
        }

        public Criteria andZizhiIsNull() {
            addCriterion("ZIZHI is null");
            return (Criteria) this;
        }

        public Criteria andZizhiIsNotNull() {
            addCriterion("ZIZHI is not null");
            return (Criteria) this;
        }

        public Criteria andZizhiEqualTo(String value) {
            addCriterion("ZIZHI =", value, "zizhi");
            return (Criteria) this;
        }

        public Criteria andZizhiNotEqualTo(String value) {
            addCriterion("ZIZHI <>", value, "zizhi");
            return (Criteria) this;
        }

        public Criteria andZizhiGreaterThan(String value) {
            addCriterion("ZIZHI >", value, "zizhi");
            return (Criteria) this;
        }

        public Criteria andZizhiGreaterThanOrEqualTo(String value) {
            addCriterion("ZIZHI >=", value, "zizhi");
            return (Criteria) this;
        }

        public Criteria andZizhiLessThan(String value) {
            addCriterion("ZIZHI <", value, "zizhi");
            return (Criteria) this;
        }

        public Criteria andZizhiLessThanOrEqualTo(String value) {
            addCriterion("ZIZHI <=", value, "zizhi");
            return (Criteria) this;
        }

        public Criteria andZizhiLike(String value) {
            addCriterion("ZIZHI like", value, "zizhi");
            return (Criteria) this;
        }

        public Criteria andZizhiNotLike(String value) {
            addCriterion("ZIZHI not like", value, "zizhi");
            return (Criteria) this;
        }

        public Criteria andZizhiIn(List<String> values) {
            addCriterion("ZIZHI in", values, "zizhi");
            return (Criteria) this;
        }

        public Criteria andZizhiNotIn(List<String> values) {
            addCriterion("ZIZHI not in", values, "zizhi");
            return (Criteria) this;
        }

        public Criteria andZizhiBetween(String value1, String value2) {
            addCriterion("ZIZHI between", value1, value2, "zizhi");
            return (Criteria) this;
        }

        public Criteria andZizhiNotBetween(String value1, String value2) {
            addCriterion("ZIZHI not between", value1, value2, "zizhi");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("UNIT is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("UNIT =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("UNIT <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("UNIT >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("UNIT >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("UNIT <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("UNIT <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("UNIT like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("UNIT not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("UNIT in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("UNIT not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("UNIT between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("UNIT not between", value1, value2, "unit");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated do_not_delete_during_merge Tue May 02 13:19:15 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JAVAOAS.T_OUT_COMPANY
     *
     * @mbg.generated Tue May 02 13:19:15 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
        
        
        
    }
}