package com.talkweb.ei.outmanager.model;

import java.util.Date;

public class TOutUserJc extends ImportObj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JC.ID
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JC.JCREASON
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    private String jcreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JC.JCDATE
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    private Date jcdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JC.GZENDDATE
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    private Date gzenddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JC.QT
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    private String qt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JC.USERID
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JC.ID
     *
     * @return the value of JAVAOAS.T_OUT_USER_JC.ID
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JC.ID
     *
     * @param id the value for JAVAOAS.T_OUT_USER_JC.ID
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JC.JCREASON
     *
     * @return the value of JAVAOAS.T_OUT_USER_JC.JCREASON
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    public String getJcreason() {
        return jcreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JC.JCREASON
     *
     * @param jcreason the value for JAVAOAS.T_OUT_USER_JC.JCREASON
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    public void setJcreason(String jcreason) {
        this.jcreason = jcreason == null ? null : jcreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JC.JCDATE
     *
     * @return the value of JAVAOAS.T_OUT_USER_JC.JCDATE
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    public Date getJcdate() {
        return jcdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JC.JCDATE
     *
     * @param jcdate the value for JAVAOAS.T_OUT_USER_JC.JCDATE
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    public void setJcdate(Date jcdate) {
        this.jcdate = jcdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JC.GZENDDATE
     *
     * @return the value of JAVAOAS.T_OUT_USER_JC.GZENDDATE
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    public Date getGzenddate() {
        return gzenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JC.GZENDDATE
     *
     * @param gzenddate the value for JAVAOAS.T_OUT_USER_JC.GZENDDATE
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    public void setGzenddate(Date gzenddate) {
        this.gzenddate = gzenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JC.QT
     *
     * @return the value of JAVAOAS.T_OUT_USER_JC.QT
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    public String getQt() {
        return qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JC.QT
     *
     * @param qt the value for JAVAOAS.T_OUT_USER_JC.QT
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    public void setQt(String qt) {
        this.qt = qt == null ? null : qt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JC.USERID
     *
     * @return the value of JAVAOAS.T_OUT_USER_JC.USERID
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JC.USERID
     *
     * @param userid the value for JAVAOAS.T_OUT_USER_JC.USERID
     *
     * @mbg.generated Wed May 24 16:24:40 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}