package com.talkweb.ei.outmanager.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TOutUserHtExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public TOutUserHtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("UNIT is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("UNIT =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("UNIT <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("UNIT >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("UNIT >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("UNIT <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("UNIT <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("UNIT like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("UNIT not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("UNIT in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("UNIT not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("UNIT between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("UNIT not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andConstatusIsNull() {
            addCriterion("CONSTATUS is null");
            return (Criteria) this;
        }

        public Criteria andConstatusIsNotNull() {
            addCriterion("CONSTATUS is not null");
            return (Criteria) this;
        }

        public Criteria andConstatusEqualTo(String value) {
            addCriterion("CONSTATUS =", value, "constatus");
            return (Criteria) this;
        }

        public Criteria andConstatusNotEqualTo(String value) {
            addCriterion("CONSTATUS <>", value, "constatus");
            return (Criteria) this;
        }

        public Criteria andConstatusGreaterThan(String value) {
            addCriterion("CONSTATUS >", value, "constatus");
            return (Criteria) this;
        }

        public Criteria andConstatusGreaterThanOrEqualTo(String value) {
            addCriterion("CONSTATUS >=", value, "constatus");
            return (Criteria) this;
        }

        public Criteria andConstatusLessThan(String value) {
            addCriterion("CONSTATUS <", value, "constatus");
            return (Criteria) this;
        }

        public Criteria andConstatusLessThanOrEqualTo(String value) {
            addCriterion("CONSTATUS <=", value, "constatus");
            return (Criteria) this;
        }

        public Criteria andConstatusLike(String value) {
            addCriterion("CONSTATUS like", value, "constatus");
            return (Criteria) this;
        }

        public Criteria andConstatusNotLike(String value) {
            addCriterion("CONSTATUS not like", value, "constatus");
            return (Criteria) this;
        }

        public Criteria andConstatusIn(List<String> values) {
            addCriterion("CONSTATUS in", values, "constatus");
            return (Criteria) this;
        }

        public Criteria andConstatusNotIn(List<String> values) {
            addCriterion("CONSTATUS not in", values, "constatus");
            return (Criteria) this;
        }

        public Criteria andConstatusBetween(String value1, String value2) {
            addCriterion("CONSTATUS between", value1, value2, "constatus");
            return (Criteria) this;
        }

        public Criteria andConstatusNotBetween(String value1, String value2) {
            addCriterion("CONSTATUS not between", value1, value2, "constatus");
            return (Criteria) this;
        }

        public Criteria andConqxtypeIsNull() {
            addCriterion("CONQXTYPE is null");
            return (Criteria) this;
        }

        public Criteria andConqxtypeIsNotNull() {
            addCriterion("CONQXTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andConqxtypeEqualTo(String value) {
            addCriterion("CONQXTYPE =", value, "conqxtype");
            return (Criteria) this;
        }

        public Criteria andConqxtypeNotEqualTo(String value) {
            addCriterion("CONQXTYPE <>", value, "conqxtype");
            return (Criteria) this;
        }

        public Criteria andConqxtypeGreaterThan(String value) {
            addCriterion("CONQXTYPE >", value, "conqxtype");
            return (Criteria) this;
        }

        public Criteria andConqxtypeGreaterThanOrEqualTo(String value) {
            addCriterion("CONQXTYPE >=", value, "conqxtype");
            return (Criteria) this;
        }

        public Criteria andConqxtypeLessThan(String value) {
            addCriterion("CONQXTYPE <", value, "conqxtype");
            return (Criteria) this;
        }

        public Criteria andConqxtypeLessThanOrEqualTo(String value) {
            addCriterion("CONQXTYPE <=", value, "conqxtype");
            return (Criteria) this;
        }

        public Criteria andConqxtypeLike(String value) {
            addCriterion("CONQXTYPE like", value, "conqxtype");
            return (Criteria) this;
        }

        public Criteria andConqxtypeNotLike(String value) {
            addCriterion("CONQXTYPE not like", value, "conqxtype");
            return (Criteria) this;
        }

        public Criteria andConqxtypeIn(List<String> values) {
            addCriterion("CONQXTYPE in", values, "conqxtype");
            return (Criteria) this;
        }

        public Criteria andConqxtypeNotIn(List<String> values) {
            addCriterion("CONQXTYPE not in", values, "conqxtype");
            return (Criteria) this;
        }

        public Criteria andConqxtypeBetween(String value1, String value2) {
            addCriterion("CONQXTYPE between", value1, value2, "conqxtype");
            return (Criteria) this;
        }

        public Criteria andConqxtypeNotBetween(String value1, String value2) {
            addCriterion("CONQXTYPE not between", value1, value2, "conqxtype");
            return (Criteria) this;
        }

        public Criteria andQixianIsNull() {
            addCriterion("QIXIAN is null");
            return (Criteria) this;
        }

        public Criteria andQixianIsNotNull() {
            addCriterion("QIXIAN is not null");
            return (Criteria) this;
        }

        public Criteria andQixianEqualTo(String value) {
            addCriterion("QIXIAN =", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianNotEqualTo(String value) {
            addCriterion("QIXIAN <>", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianGreaterThan(String value) {
            addCriterion("QIXIAN >", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianGreaterThanOrEqualTo(String value) {
            addCriterion("QIXIAN >=", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianLessThan(String value) {
            addCriterion("QIXIAN <", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianLessThanOrEqualTo(String value) {
            addCriterion("QIXIAN <=", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianLike(String value) {
            addCriterion("QIXIAN like", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianNotLike(String value) {
            addCriterion("QIXIAN not like", value, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianIn(List<String> values) {
            addCriterion("QIXIAN in", values, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianNotIn(List<String> values) {
            addCriterion("QIXIAN not in", values, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianBetween(String value1, String value2) {
            addCriterion("QIXIAN between", value1, value2, "qixian");
            return (Criteria) this;
        }

        public Criteria andQixianNotBetween(String value1, String value2) {
            addCriterion("QIXIAN not between", value1, value2, "qixian");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNull() {
            addCriterion("STARTDATE is null");
            return (Criteria) this;
        }

        public Criteria andStartdateIsNotNull() {
            addCriterion("STARTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andStartdateEqualTo(Date value) {
            addCriterionForJDBCDate("STARTDATE =", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("STARTDATE <>", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThan(Date value) {
            addCriterionForJDBCDate("STARTDATE >", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("STARTDATE >=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThan(Date value) {
            addCriterionForJDBCDate("STARTDATE <", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("STARTDATE <=", value, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateIn(List<Date> values) {
            addCriterionForJDBCDate("STARTDATE in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("STARTDATE not in", values, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("STARTDATE between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andStartdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("STARTDATE not between", value1, value2, "startdate");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("ENDDATE is null");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("ENDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andEnddateEqualTo(Date value) {
            addCriterionForJDBCDate("ENDDATE =", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotEqualTo(Date value) {
            addCriterionForJDBCDate("ENDDATE <>", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThan(Date value) {
            addCriterionForJDBCDate("ENDDATE >", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ENDDATE >=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThan(Date value) {
            addCriterionForJDBCDate("ENDDATE <", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ENDDATE <=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateIn(List<Date> values) {
            addCriterionForJDBCDate("ENDDATE in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotIn(List<Date> values) {
            addCriterionForJDBCDate("ENDDATE not in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ENDDATE between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ENDDATE not between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andConnumberIsNull() {
            addCriterion("CONNUMBER is null");
            return (Criteria) this;
        }

        public Criteria andConnumberIsNotNull() {
            addCriterion("CONNUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andConnumberEqualTo(String value) {
            addCriterion("CONNUMBER =", value, "connumber");
            return (Criteria) this;
        }

        public Criteria andConnumberNotEqualTo(String value) {
            addCriterion("CONNUMBER <>", value, "connumber");
            return (Criteria) this;
        }

        public Criteria andConnumberGreaterThan(String value) {
            addCriterion("CONNUMBER >", value, "connumber");
            return (Criteria) this;
        }

        public Criteria andConnumberGreaterThanOrEqualTo(String value) {
            addCriterion("CONNUMBER >=", value, "connumber");
            return (Criteria) this;
        }

        public Criteria andConnumberLessThan(String value) {
            addCriterion("CONNUMBER <", value, "connumber");
            return (Criteria) this;
        }

        public Criteria andConnumberLessThanOrEqualTo(String value) {
            addCriterion("CONNUMBER <=", value, "connumber");
            return (Criteria) this;
        }

        public Criteria andConnumberLike(String value) {
            addCriterion("CONNUMBER like", value, "connumber");
            return (Criteria) this;
        }

        public Criteria andConnumberNotLike(String value) {
            addCriterion("CONNUMBER not like", value, "connumber");
            return (Criteria) this;
        }

        public Criteria andConnumberIn(List<String> values) {
            addCriterion("CONNUMBER in", values, "connumber");
            return (Criteria) this;
        }

        public Criteria andConnumberNotIn(List<String> values) {
            addCriterion("CONNUMBER not in", values, "connumber");
            return (Criteria) this;
        }

        public Criteria andConnumberBetween(String value1, String value2) {
            addCriterion("CONNUMBER between", value1, value2, "connumber");
            return (Criteria) this;
        }

        public Criteria andConnumberNotBetween(String value1, String value2) {
            addCriterion("CONNUMBER not between", value1, value2, "connumber");
            return (Criteria) this;
        }

        public Criteria andContypeIsNull() {
            addCriterion("CONTYPE is null");
            return (Criteria) this;
        }

        public Criteria andContypeIsNotNull() {
            addCriterion("CONTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andContypeEqualTo(String value) {
            addCriterion("CONTYPE =", value, "contype");
            return (Criteria) this;
        }

        public Criteria andContypeNotEqualTo(String value) {
            addCriterion("CONTYPE <>", value, "contype");
            return (Criteria) this;
        }

        public Criteria andContypeGreaterThan(String value) {
            addCriterion("CONTYPE >", value, "contype");
            return (Criteria) this;
        }

        public Criteria andContypeGreaterThanOrEqualTo(String value) {
            addCriterion("CONTYPE >=", value, "contype");
            return (Criteria) this;
        }

        public Criteria andContypeLessThan(String value) {
            addCriterion("CONTYPE <", value, "contype");
            return (Criteria) this;
        }

        public Criteria andContypeLessThanOrEqualTo(String value) {
            addCriterion("CONTYPE <=", value, "contype");
            return (Criteria) this;
        }

        public Criteria andContypeLike(String value) {
            addCriterion("CONTYPE like", value, "contype");
            return (Criteria) this;
        }

        public Criteria andContypeNotLike(String value) {
            addCriterion("CONTYPE not like", value, "contype");
            return (Criteria) this;
        }

        public Criteria andContypeIn(List<String> values) {
            addCriterion("CONTYPE in", values, "contype");
            return (Criteria) this;
        }

        public Criteria andContypeNotIn(List<String> values) {
            addCriterion("CONTYPE not in", values, "contype");
            return (Criteria) this;
        }

        public Criteria andContypeBetween(String value1, String value2) {
            addCriterion("CONTYPE between", value1, value2, "contype");
            return (Criteria) this;
        }

        public Criteria andContypeNotBetween(String value1, String value2) {
            addCriterion("CONTYPE not between", value1, value2, "contype");
            return (Criteria) this;
        }

        public Criteria andFristunitIsNull() {
            addCriterion("FRISTUNIT is null");
            return (Criteria) this;
        }

        public Criteria andFristunitIsNotNull() {
            addCriterion("FRISTUNIT is not null");
            return (Criteria) this;
        }

        public Criteria andFristunitEqualTo(String value) {
            addCriterion("FRISTUNIT =", value, "fristunit");
            return (Criteria) this;
        }

        public Criteria andFristunitNotEqualTo(String value) {
            addCriterion("FRISTUNIT <>", value, "fristunit");
            return (Criteria) this;
        }

        public Criteria andFristunitGreaterThan(String value) {
            addCriterion("FRISTUNIT >", value, "fristunit");
            return (Criteria) this;
        }

        public Criteria andFristunitGreaterThanOrEqualTo(String value) {
            addCriterion("FRISTUNIT >=", value, "fristunit");
            return (Criteria) this;
        }

        public Criteria andFristunitLessThan(String value) {
            addCriterion("FRISTUNIT <", value, "fristunit");
            return (Criteria) this;
        }

        public Criteria andFristunitLessThanOrEqualTo(String value) {
            addCriterion("FRISTUNIT <=", value, "fristunit");
            return (Criteria) this;
        }

        public Criteria andFristunitLike(String value) {
            addCriterion("FRISTUNIT like", value, "fristunit");
            return (Criteria) this;
        }

        public Criteria andFristunitNotLike(String value) {
            addCriterion("FRISTUNIT not like", value, "fristunit");
            return (Criteria) this;
        }

        public Criteria andFristunitIn(List<String> values) {
            addCriterion("FRISTUNIT in", values, "fristunit");
            return (Criteria) this;
        }

        public Criteria andFristunitNotIn(List<String> values) {
            addCriterion("FRISTUNIT not in", values, "fristunit");
            return (Criteria) this;
        }

        public Criteria andFristunitBetween(String value1, String value2) {
            addCriterion("FRISTUNIT between", value1, value2, "fristunit");
            return (Criteria) this;
        }

        public Criteria andFristunitNotBetween(String value1, String value2) {
            addCriterion("FRISTUNIT not between", value1, value2, "fristunit");
            return (Criteria) this;
        }

        public Criteria andNwconnumberIsNull() {
            addCriterion("NWCONNUMBER is null");
            return (Criteria) this;
        }

        public Criteria andNwconnumberIsNotNull() {
            addCriterion("NWCONNUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andNwconnumberEqualTo(String value) {
            addCriterion("NWCONNUMBER =", value, "nwconnumber");
            return (Criteria) this;
        }

        public Criteria andNwconnumberNotEqualTo(String value) {
            addCriterion("NWCONNUMBER <>", value, "nwconnumber");
            return (Criteria) this;
        }

        public Criteria andNwconnumberGreaterThan(String value) {
            addCriterion("NWCONNUMBER >", value, "nwconnumber");
            return (Criteria) this;
        }

        public Criteria andNwconnumberGreaterThanOrEqualTo(String value) {
            addCriterion("NWCONNUMBER >=", value, "nwconnumber");
            return (Criteria) this;
        }

        public Criteria andNwconnumberLessThan(String value) {
            addCriterion("NWCONNUMBER <", value, "nwconnumber");
            return (Criteria) this;
        }

        public Criteria andNwconnumberLessThanOrEqualTo(String value) {
            addCriterion("NWCONNUMBER <=", value, "nwconnumber");
            return (Criteria) this;
        }

        public Criteria andNwconnumberLike(String value) {
            addCriterion("NWCONNUMBER like", value, "nwconnumber");
            return (Criteria) this;
        }

        public Criteria andNwconnumberNotLike(String value) {
            addCriterion("NWCONNUMBER not like", value, "nwconnumber");
            return (Criteria) this;
        }

        public Criteria andNwconnumberIn(List<String> values) {
            addCriterion("NWCONNUMBER in", values, "nwconnumber");
            return (Criteria) this;
        }

        public Criteria andNwconnumberNotIn(List<String> values) {
            addCriterion("NWCONNUMBER not in", values, "nwconnumber");
            return (Criteria) this;
        }

        public Criteria andNwconnumberBetween(String value1, String value2) {
            addCriterion("NWCONNUMBER between", value1, value2, "nwconnumber");
            return (Criteria) this;
        }

        public Criteria andNwconnumberNotBetween(String value1, String value2) {
            addCriterion("NWCONNUMBER not between", value1, value2, "nwconnumber");
            return (Criteria) this;
        }

        public Criteria andLwconnameIsNull() {
            addCriterion("LWCONNAME is null");
            return (Criteria) this;
        }

        public Criteria andLwconnameIsNotNull() {
            addCriterion("LWCONNAME is not null");
            return (Criteria) this;
        }

        public Criteria andLwconnameEqualTo(String value) {
            addCriterion("LWCONNAME =", value, "lwconname");
            return (Criteria) this;
        }

        public Criteria andLwconnameNotEqualTo(String value) {
            addCriterion("LWCONNAME <>", value, "lwconname");
            return (Criteria) this;
        }

        public Criteria andLwconnameGreaterThan(String value) {
            addCriterion("LWCONNAME >", value, "lwconname");
            return (Criteria) this;
        }

        public Criteria andLwconnameGreaterThanOrEqualTo(String value) {
            addCriterion("LWCONNAME >=", value, "lwconname");
            return (Criteria) this;
        }

        public Criteria andLwconnameLessThan(String value) {
            addCriterion("LWCONNAME <", value, "lwconname");
            return (Criteria) this;
        }

        public Criteria andLwconnameLessThanOrEqualTo(String value) {
            addCriterion("LWCONNAME <=", value, "lwconname");
            return (Criteria) this;
        }

        public Criteria andLwconnameLike(String value) {
            addCriterion("LWCONNAME like", value, "lwconname");
            return (Criteria) this;
        }

        public Criteria andLwconnameNotLike(String value) {
            addCriterion("LWCONNAME not like", value, "lwconname");
            return (Criteria) this;
        }

        public Criteria andLwconnameIn(List<String> values) {
            addCriterion("LWCONNAME in", values, "lwconname");
            return (Criteria) this;
        }

        public Criteria andLwconnameNotIn(List<String> values) {
            addCriterion("LWCONNAME not in", values, "lwconname");
            return (Criteria) this;
        }

        public Criteria andLwconnameBetween(String value1, String value2) {
            addCriterion("LWCONNAME between", value1, value2, "lwconname");
            return (Criteria) this;
        }

        public Criteria andLwconnameNotBetween(String value1, String value2) {
            addCriterion("LWCONNAME not between", value1, value2, "lwconname");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(String value) {
            addCriterion("USERID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(String value) {
            addCriterion("USERID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(String value) {
            addCriterion("USERID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(String value) {
            addCriterion("USERID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(String value) {
            addCriterion("USERID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(String value) {
            addCriterion("USERID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLike(String value) {
            addCriterion("USERID like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotLike(String value) {
            addCriterion("USERID not like", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<String> values) {
            addCriterion("USERID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<String> values) {
            addCriterion("USERID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(String value1, String value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(String value1, String value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated do_not_delete_during_merge Wed May 24 16:24:12 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JAVAOAS.T_OUT_USER_HT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}