package com.talkweb.ei.outmanager.model;

import java.util.Date;

public class TOutUserJyinfo extends ImportObj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.ID
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.SCHOOL
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.STARTDATE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.ENDDATE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.XUELI
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String xueli;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.XUELIZSNUMBER
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String xuelizsnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.ISMAXXL
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String ismaxxl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.ISQRZ
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String isqrz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.XUEWEI
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String xuewei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.D1XWTYPE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String d1xwtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.D2XWTYPE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String d2xwtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.XWDATE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private Date xwdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.XWUNIT
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String xwunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.XWZSNUMBER
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String xwzsnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.ISMAXXW
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String ismaxxw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.TDXL
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String tdxl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.XDBY
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String xdby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.ZYTYPE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String zytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.ZYSUBTYPE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String zysubtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.D1ZY
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String d1zy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.D2ZY
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String d2zy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.XUEZHI
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String xuezhi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.XXXS
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String xxxs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.XXQK
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String xxqk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.QT
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String qt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_JYINFO.USERID
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ID
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.ID
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ID
     *
     * @param id the value for JAVAOAS.T_OUT_USER_JYINFO.ID
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.SCHOOL
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.SCHOOL
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.SCHOOL
     *
     * @param school the value for JAVAOAS.T_OUT_USER_JYINFO.SCHOOL
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.STARTDATE
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.STARTDATE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.STARTDATE
     *
     * @param startdate the value for JAVAOAS.T_OUT_USER_JYINFO.STARTDATE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ENDDATE
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.ENDDATE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ENDDATE
     *
     * @param enddate the value for JAVAOAS.T_OUT_USER_JYINFO.ENDDATE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XUELI
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.XUELI
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getXueli() {
        return xueli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XUELI
     *
     * @param xueli the value for JAVAOAS.T_OUT_USER_JYINFO.XUELI
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setXueli(String xueli) {
        this.xueli = xueli == null ? null : xueli.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XUELIZSNUMBER
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.XUELIZSNUMBER
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getXuelizsnumber() {
        return xuelizsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XUELIZSNUMBER
     *
     * @param xuelizsnumber the value for JAVAOAS.T_OUT_USER_JYINFO.XUELIZSNUMBER
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setXuelizsnumber(String xuelizsnumber) {
        this.xuelizsnumber = xuelizsnumber == null ? null : xuelizsnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ISMAXXL
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.ISMAXXL
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getIsmaxxl() {
        return ismaxxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ISMAXXL
     *
     * @param ismaxxl the value for JAVAOAS.T_OUT_USER_JYINFO.ISMAXXL
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setIsmaxxl(String ismaxxl) {
        this.ismaxxl = ismaxxl == null ? null : ismaxxl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ISQRZ
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.ISQRZ
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getIsqrz() {
        return isqrz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ISQRZ
     *
     * @param isqrz the value for JAVAOAS.T_OUT_USER_JYINFO.ISQRZ
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setIsqrz(String isqrz) {
        this.isqrz = isqrz == null ? null : isqrz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XUEWEI
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.XUEWEI
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getXuewei() {
        return xuewei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XUEWEI
     *
     * @param xuewei the value for JAVAOAS.T_OUT_USER_JYINFO.XUEWEI
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setXuewei(String xuewei) {
        this.xuewei = xuewei == null ? null : xuewei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.D1XWTYPE
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.D1XWTYPE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getD1xwtype() {
        return d1xwtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.D1XWTYPE
     *
     * @param d1xwtype the value for JAVAOAS.T_OUT_USER_JYINFO.D1XWTYPE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setD1xwtype(String d1xwtype) {
        this.d1xwtype = d1xwtype == null ? null : d1xwtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.D2XWTYPE
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.D2XWTYPE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getD2xwtype() {
        return d2xwtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.D2XWTYPE
     *
     * @param d2xwtype the value for JAVAOAS.T_OUT_USER_JYINFO.D2XWTYPE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setD2xwtype(String d2xwtype) {
        this.d2xwtype = d2xwtype == null ? null : d2xwtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XWDATE
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.XWDATE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public Date getXwdate() {
        return xwdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XWDATE
     *
     * @param xwdate the value for JAVAOAS.T_OUT_USER_JYINFO.XWDATE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setXwdate(Date xwdate) {
        this.xwdate = xwdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XWUNIT
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.XWUNIT
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getXwunit() {
        return xwunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XWUNIT
     *
     * @param xwunit the value for JAVAOAS.T_OUT_USER_JYINFO.XWUNIT
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setXwunit(String xwunit) {
        this.xwunit = xwunit == null ? null : xwunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XWZSNUMBER
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.XWZSNUMBER
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getXwzsnumber() {
        return xwzsnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XWZSNUMBER
     *
     * @param xwzsnumber the value for JAVAOAS.T_OUT_USER_JYINFO.XWZSNUMBER
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setXwzsnumber(String xwzsnumber) {
        this.xwzsnumber = xwzsnumber == null ? null : xwzsnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ISMAXXW
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.ISMAXXW
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getIsmaxxw() {
        return ismaxxw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ISMAXXW
     *
     * @param ismaxxw the value for JAVAOAS.T_OUT_USER_JYINFO.ISMAXXW
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setIsmaxxw(String ismaxxw) {
        this.ismaxxw = ismaxxw == null ? null : ismaxxw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.TDXL
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.TDXL
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getTdxl() {
        return tdxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.TDXL
     *
     * @param tdxl the value for JAVAOAS.T_OUT_USER_JYINFO.TDXL
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setTdxl(String tdxl) {
        this.tdxl = tdxl == null ? null : tdxl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XDBY
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.XDBY
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getXdby() {
        return xdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XDBY
     *
     * @param xdby the value for JAVAOAS.T_OUT_USER_JYINFO.XDBY
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setXdby(String xdby) {
        this.xdby = xdby == null ? null : xdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ZYTYPE
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.ZYTYPE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getZytype() {
        return zytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ZYTYPE
     *
     * @param zytype the value for JAVAOAS.T_OUT_USER_JYINFO.ZYTYPE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setZytype(String zytype) {
        this.zytype = zytype == null ? null : zytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ZYSUBTYPE
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.ZYSUBTYPE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getZysubtype() {
        return zysubtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.ZYSUBTYPE
     *
     * @param zysubtype the value for JAVAOAS.T_OUT_USER_JYINFO.ZYSUBTYPE
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setZysubtype(String zysubtype) {
        this.zysubtype = zysubtype == null ? null : zysubtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.D1ZY
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.D1ZY
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getD1zy() {
        return d1zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.D1ZY
     *
     * @param d1zy the value for JAVAOAS.T_OUT_USER_JYINFO.D1ZY
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setD1zy(String d1zy) {
        this.d1zy = d1zy == null ? null : d1zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.D2ZY
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.D2ZY
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getD2zy() {
        return d2zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.D2ZY
     *
     * @param d2zy the value for JAVAOAS.T_OUT_USER_JYINFO.D2ZY
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setD2zy(String d2zy) {
        this.d2zy = d2zy == null ? null : d2zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XUEZHI
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.XUEZHI
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getXuezhi() {
        return xuezhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XUEZHI
     *
     * @param xuezhi the value for JAVAOAS.T_OUT_USER_JYINFO.XUEZHI
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setXuezhi(String xuezhi) {
        this.xuezhi = xuezhi == null ? null : xuezhi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XXXS
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.XXXS
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getXxxs() {
        return xxxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XXXS
     *
     * @param xxxs the value for JAVAOAS.T_OUT_USER_JYINFO.XXXS
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setXxxs(String xxxs) {
        this.xxxs = xxxs == null ? null : xxxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XXQK
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.XXQK
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getXxqk() {
        return xxqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.XXQK
     *
     * @param xxqk the value for JAVAOAS.T_OUT_USER_JYINFO.XXQK
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setXxqk(String xxqk) {
        this.xxqk = xxqk == null ? null : xxqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.QT
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.QT
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getQt() {
        return qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.QT
     *
     * @param qt the value for JAVAOAS.T_OUT_USER_JYINFO.QT
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setQt(String qt) {
        this.qt = qt == null ? null : qt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_JYINFO.USERID
     *
     * @return the value of JAVAOAS.T_OUT_USER_JYINFO.USERID
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_JYINFO.USERID
     *
     * @param userid the value for JAVAOAS.T_OUT_USER_JYINFO.USERID
     *
     * @mbg.generated Wed May 31 09:45:25 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}