package com.talkweb.ei.outmanager.model;

import java.math.BigDecimal;

public class TOutJthy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_JTHY.ID
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_JTHY.MONTH
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    private String month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_JTHY.UNIT
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_JTHY.COMPANYID
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    private String companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_JTHY.CONCODE
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    private String concode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_JTHY.GHHY
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    private BigDecimal ghhy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_JTHY.GLH
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    private BigDecimal glh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_JTHY.SHUIJIN
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    private BigDecimal shuijin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_JTHY.QT
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    private BigDecimal qt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_JTHY.LZRHY
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    private BigDecimal lzrhy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_JTHY.REMARK
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_JTHY.ID
     *
     * @return the value of JAVAOAS.T_OUT_JTHY.ID
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_JTHY.ID
     *
     * @param id the value for JAVAOAS.T_OUT_JTHY.ID
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_JTHY.MONTH
     *
     * @return the value of JAVAOAS.T_OUT_JTHY.MONTH
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_JTHY.MONTH
     *
     * @param month the value for JAVAOAS.T_OUT_JTHY.MONTH
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_JTHY.UNIT
     *
     * @return the value of JAVAOAS.T_OUT_JTHY.UNIT
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_JTHY.UNIT
     *
     * @param unit the value for JAVAOAS.T_OUT_JTHY.UNIT
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_JTHY.COMPANYID
     *
     * @return the value of JAVAOAS.T_OUT_JTHY.COMPANYID
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public String getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_JTHY.COMPANYID
     *
     * @param companyid the value for JAVAOAS.T_OUT_JTHY.COMPANYID
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public void setCompanyid(String companyid) {
        this.companyid = companyid == null ? null : companyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_JTHY.CONCODE
     *
     * @return the value of JAVAOAS.T_OUT_JTHY.CONCODE
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public String getConcode() {
        return concode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_JTHY.CONCODE
     *
     * @param concode the value for JAVAOAS.T_OUT_JTHY.CONCODE
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public void setConcode(String concode) {
        this.concode = concode == null ? null : concode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_JTHY.GHHY
     *
     * @return the value of JAVAOAS.T_OUT_JTHY.GHHY
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public BigDecimal getGhhy() {
        return ghhy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_JTHY.GHHY
     *
     * @param ghhy the value for JAVAOAS.T_OUT_JTHY.GHHY
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public void setGhhy(BigDecimal ghhy) {
        this.ghhy = ghhy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_JTHY.GLH
     *
     * @return the value of JAVAOAS.T_OUT_JTHY.GLH
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public BigDecimal getGlh() {
        return glh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_JTHY.GLH
     *
     * @param glh the value for JAVAOAS.T_OUT_JTHY.GLH
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public void setGlh(BigDecimal glh) {
        this.glh = glh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_JTHY.SHUIJIN
     *
     * @return the value of JAVAOAS.T_OUT_JTHY.SHUIJIN
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public BigDecimal getShuijin() {
        return shuijin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_JTHY.SHUIJIN
     *
     * @param shuijin the value for JAVAOAS.T_OUT_JTHY.SHUIJIN
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public void setShuijin(BigDecimal shuijin) {
        this.shuijin = shuijin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_JTHY.QT
     *
     * @return the value of JAVAOAS.T_OUT_JTHY.QT
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public BigDecimal getQt() {
        return qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_JTHY.QT
     *
     * @param qt the value for JAVAOAS.T_OUT_JTHY.QT
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public void setQt(BigDecimal qt) {
        this.qt = qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_JTHY.LZRHY
     *
     * @return the value of JAVAOAS.T_OUT_JTHY.LZRHY
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public BigDecimal getLzrhy() {
        return lzrhy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_JTHY.LZRHY
     *
     * @param lzrhy the value for JAVAOAS.T_OUT_JTHY.LZRHY
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public void setLzrhy(BigDecimal lzrhy) {
        this.lzrhy = lzrhy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_JTHY.REMARK
     *
     * @return the value of JAVAOAS.T_OUT_JTHY.REMARK
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_JTHY.REMARK
     *
     * @param remark the value for JAVAOAS.T_OUT_JTHY.REMARK
     *
     * @mbg.generated Mon Jun 05 15:25:07 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}