package com.talkweb.ei.outmanager.model;

import java.util.Date;

public class TOutReportst {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_REPORTST.ID
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_REPORTST.REPDATE
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    private Date repdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_REPORTST.UNIT
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_REPORTST.REPTYPE
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    private String reptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_REPORTST.INTF
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    private String intf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_REPORTST.ISRECREATE
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    private String isrecreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_REPORTST.REMARK
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_REPORTST.CREATEDATE
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_REPORTST.ID
     *
     * @return the value of JAVAOAS.T_OUT_REPORTST.ID
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_REPORTST.ID
     *
     * @param id the value for JAVAOAS.T_OUT_REPORTST.ID
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_REPORTST.REPDATE
     *
     * @return the value of JAVAOAS.T_OUT_REPORTST.REPDATE
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public Date getRepdate() {
        return repdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_REPORTST.REPDATE
     *
     * @param repdate the value for JAVAOAS.T_OUT_REPORTST.REPDATE
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public void setRepdate(Date repdate) {
        this.repdate = repdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_REPORTST.UNIT
     *
     * @return the value of JAVAOAS.T_OUT_REPORTST.UNIT
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_REPORTST.UNIT
     *
     * @param unit the value for JAVAOAS.T_OUT_REPORTST.UNIT
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_REPORTST.REPTYPE
     *
     * @return the value of JAVAOAS.T_OUT_REPORTST.REPTYPE
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public String getReptype() {
        return reptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_REPORTST.REPTYPE
     *
     * @param reptype the value for JAVAOAS.T_OUT_REPORTST.REPTYPE
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public void setReptype(String reptype) {
        this.reptype = reptype == null ? null : reptype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_REPORTST.INTF
     *
     * @return the value of JAVAOAS.T_OUT_REPORTST.INTF
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public String getIntf() {
        return intf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_REPORTST.INTF
     *
     * @param intf the value for JAVAOAS.T_OUT_REPORTST.INTF
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public void setIntf(String intf) {
        this.intf = intf == null ? null : intf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_REPORTST.ISRECREATE
     *
     * @return the value of JAVAOAS.T_OUT_REPORTST.ISRECREATE
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public String getIsrecreate() {
        return isrecreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_REPORTST.ISRECREATE
     *
     * @param isrecreate the value for JAVAOAS.T_OUT_REPORTST.ISRECREATE
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public void setIsrecreate(String isrecreate) {
        this.isrecreate = isrecreate == null ? null : isrecreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_REPORTST.REMARK
     *
     * @return the value of JAVAOAS.T_OUT_REPORTST.REMARK
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_REPORTST.REMARK
     *
     * @param remark the value for JAVAOAS.T_OUT_REPORTST.REMARK
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_REPORTST.CREATEDATE
     *
     * @return the value of JAVAOAS.T_OUT_REPORTST.CREATEDATE
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_REPORTST.CREATEDATE
     *
     * @param createdate the value for JAVAOAS.T_OUT_REPORTST.CREATEDATE
     *
     * @mbg.generated Tue Jul 18 17:13:40 CST 2017
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}