package com.talkweb.ei.outmanager.model;

import java.util.Date;

public class TOutUserHt extends ImportObj {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.ID
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.UNIT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.CONSTATUS
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private String constatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.CONQXTYPE
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private String conqxtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.QIXIAN
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private String qixian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.STARTDATE
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.ENDDATE
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.CONNUMBER
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private String connumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.CONTYPE
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private String contype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.FRISTUNIT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private String fristunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.NWCONNUMBER
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private String nwconnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.LWCONNAME
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private String lwconname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.T_OUT_USER_HT.USERID
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.ID
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.ID
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.ID
     *
     * @param id the value for JAVAOAS.T_OUT_USER_HT.ID
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.UNIT
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.UNIT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.UNIT
     *
     * @param unit the value for JAVAOAS.T_OUT_USER_HT.UNIT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.CONSTATUS
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.CONSTATUS
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public String getConstatus() {
        return constatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.CONSTATUS
     *
     * @param constatus the value for JAVAOAS.T_OUT_USER_HT.CONSTATUS
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setConstatus(String constatus) {
        this.constatus = constatus == null ? null : constatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.CONQXTYPE
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.CONQXTYPE
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public String getConqxtype() {
        return conqxtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.CONQXTYPE
     *
     * @param conqxtype the value for JAVAOAS.T_OUT_USER_HT.CONQXTYPE
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setConqxtype(String conqxtype) {
        this.conqxtype = conqxtype == null ? null : conqxtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.QIXIAN
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.QIXIAN
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public String getQixian() {
        return qixian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.QIXIAN
     *
     * @param qixian the value for JAVAOAS.T_OUT_USER_HT.QIXIAN
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setQixian(String qixian) {
        this.qixian = qixian == null ? null : qixian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.STARTDATE
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.STARTDATE
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.STARTDATE
     *
     * @param startdate the value for JAVAOAS.T_OUT_USER_HT.STARTDATE
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.ENDDATE
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.ENDDATE
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.ENDDATE
     *
     * @param enddate the value for JAVAOAS.T_OUT_USER_HT.ENDDATE
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.CONNUMBER
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.CONNUMBER
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public String getConnumber() {
        return connumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.CONNUMBER
     *
     * @param connumber the value for JAVAOAS.T_OUT_USER_HT.CONNUMBER
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setConnumber(String connumber) {
        this.connumber = connumber == null ? null : connumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.CONTYPE
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.CONTYPE
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public String getContype() {
        return contype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.CONTYPE
     *
     * @param contype the value for JAVAOAS.T_OUT_USER_HT.CONTYPE
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setContype(String contype) {
        this.contype = contype == null ? null : contype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.FRISTUNIT
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.FRISTUNIT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public String getFristunit() {
        return fristunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.FRISTUNIT
     *
     * @param fristunit the value for JAVAOAS.T_OUT_USER_HT.FRISTUNIT
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setFristunit(String fristunit) {
        this.fristunit = fristunit == null ? null : fristunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.NWCONNUMBER
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.NWCONNUMBER
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public String getNwconnumber() {
        return nwconnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.NWCONNUMBER
     *
     * @param nwconnumber the value for JAVAOAS.T_OUT_USER_HT.NWCONNUMBER
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setNwconnumber(String nwconnumber) {
        this.nwconnumber = nwconnumber == null ? null : nwconnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.LWCONNAME
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.LWCONNAME
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public String getLwconname() {
        return lwconname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.LWCONNAME
     *
     * @param lwconname the value for JAVAOAS.T_OUT_USER_HT.LWCONNAME
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setLwconname(String lwconname) {
        this.lwconname = lwconname == null ? null : lwconname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.T_OUT_USER_HT.USERID
     *
     * @return the value of JAVAOAS.T_OUT_USER_HT.USERID
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.T_OUT_USER_HT.USERID
     *
     * @param userid the value for JAVAOAS.T_OUT_USER_HT.USERID
     *
     * @mbg.generated Wed May 24 16:24:12 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }
}