package com.talkweb.ei.outmanager.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TOutJthyExample extends ExampleObj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    public TOutJthyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMonthIsNull() {
            addCriterion("MONTH is null");
            return (Criteria) this;
        }

        public Criteria andMonthIsNotNull() {
            addCriterion("MONTH is not null");
            return (Criteria) this;
        }

        public Criteria andMonthEqualTo(String value) {
            addCriterion("MONTH =", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotEqualTo(String value) {
            addCriterion("MONTH <>", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThan(String value) {
            addCriterion("MONTH >", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthGreaterThanOrEqualTo(String value) {
            addCriterion("MONTH >=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThan(String value) {
            addCriterion("MONTH <", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLessThanOrEqualTo(String value) {
            addCriterion("MONTH <=", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthLike(String value) {
            addCriterion("MONTH like", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotLike(String value) {
            addCriterion("MONTH not like", value, "month");
            return (Criteria) this;
        }

        public Criteria andMonthIn(List<String> values) {
            addCriterion("MONTH in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotIn(List<String> values) {
            addCriterion("MONTH not in", values, "month");
            return (Criteria) this;
        }

        public Criteria andMonthBetween(String value1, String value2) {
            addCriterion("MONTH between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andMonthNotBetween(String value1, String value2) {
            addCriterion("MONTH not between", value1, value2, "month");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("UNIT is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("UNIT =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("UNIT <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("UNIT >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("UNIT >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("UNIT <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("UNIT <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("UNIT like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("UNIT not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("UNIT in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("UNIT not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("UNIT between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("UNIT not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andCompanyidIsNull() {
            addCriterion("COMPANYID is null");
            return (Criteria) this;
        }

        public Criteria andCompanyidIsNotNull() {
            addCriterion("COMPANYID is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyidEqualTo(String value) {
            addCriterion("COMPANYID =", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidNotEqualTo(String value) {
            addCriterion("COMPANYID <>", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidGreaterThan(String value) {
            addCriterion("COMPANYID >", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANYID >=", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidLessThan(String value) {
            addCriterion("COMPANYID <", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidLessThanOrEqualTo(String value) {
            addCriterion("COMPANYID <=", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidLike(String value) {
            addCriterion("COMPANYID like", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidNotLike(String value) {
            addCriterion("COMPANYID not like", value, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidIn(List<String> values) {
            addCriterion("COMPANYID in", values, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidNotIn(List<String> values) {
            addCriterion("COMPANYID not in", values, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidBetween(String value1, String value2) {
            addCriterion("COMPANYID between", value1, value2, "companyid");
            return (Criteria) this;
        }

        public Criteria andCompanyidNotBetween(String value1, String value2) {
            addCriterion("COMPANYID not between", value1, value2, "companyid");
            return (Criteria) this;
        }

        public Criteria andConcodeIsNull() {
            addCriterion("CONCODE is null");
            return (Criteria) this;
        }

        public Criteria andConcodeIsNotNull() {
            addCriterion("CONCODE is not null");
            return (Criteria) this;
        }

        public Criteria andConcodeEqualTo(String value) {
            addCriterion("CONCODE =", value, "concode");
            return (Criteria) this;
        }

        public Criteria andConcodeNotEqualTo(String value) {
            addCriterion("CONCODE <>", value, "concode");
            return (Criteria) this;
        }

        public Criteria andConcodeGreaterThan(String value) {
            addCriterion("CONCODE >", value, "concode");
            return (Criteria) this;
        }

        public Criteria andConcodeGreaterThanOrEqualTo(String value) {
            addCriterion("CONCODE >=", value, "concode");
            return (Criteria) this;
        }

        public Criteria andConcodeLessThan(String value) {
            addCriterion("CONCODE <", value, "concode");
            return (Criteria) this;
        }

        public Criteria andConcodeLessThanOrEqualTo(String value) {
            addCriterion("CONCODE <=", value, "concode");
            return (Criteria) this;
        }

        public Criteria andConcodeLike(String value) {
            addCriterion("CONCODE like", value, "concode");
            return (Criteria) this;
        }

        public Criteria andConcodeNotLike(String value) {
            addCriterion("CONCODE not like", value, "concode");
            return (Criteria) this;
        }

        public Criteria andConcodeIn(List<String> values) {
            addCriterion("CONCODE in", values, "concode");
            return (Criteria) this;
        }

        public Criteria andConcodeNotIn(List<String> values) {
            addCriterion("CONCODE not in", values, "concode");
            return (Criteria) this;
        }

        public Criteria andConcodeBetween(String value1, String value2) {
            addCriterion("CONCODE between", value1, value2, "concode");
            return (Criteria) this;
        }

        public Criteria andConcodeNotBetween(String value1, String value2) {
            addCriterion("CONCODE not between", value1, value2, "concode");
            return (Criteria) this;
        }

        public Criteria andGhhyIsNull() {
            addCriterion("GHHY is null");
            return (Criteria) this;
        }

        public Criteria andGhhyIsNotNull() {
            addCriterion("GHHY is not null");
            return (Criteria) this;
        }

        public Criteria andGhhyEqualTo(BigDecimal value) {
            addCriterion("GHHY =", value, "ghhy");
            return (Criteria) this;
        }

        public Criteria andGhhyNotEqualTo(BigDecimal value) {
            addCriterion("GHHY <>", value, "ghhy");
            return (Criteria) this;
        }

        public Criteria andGhhyGreaterThan(BigDecimal value) {
            addCriterion("GHHY >", value, "ghhy");
            return (Criteria) this;
        }

        public Criteria andGhhyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GHHY >=", value, "ghhy");
            return (Criteria) this;
        }

        public Criteria andGhhyLessThan(BigDecimal value) {
            addCriterion("GHHY <", value, "ghhy");
            return (Criteria) this;
        }

        public Criteria andGhhyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GHHY <=", value, "ghhy");
            return (Criteria) this;
        }

        public Criteria andGhhyIn(List<BigDecimal> values) {
            addCriterion("GHHY in", values, "ghhy");
            return (Criteria) this;
        }

        public Criteria andGhhyNotIn(List<BigDecimal> values) {
            addCriterion("GHHY not in", values, "ghhy");
            return (Criteria) this;
        }

        public Criteria andGhhyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GHHY between", value1, value2, "ghhy");
            return (Criteria) this;
        }

        public Criteria andGhhyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GHHY not between", value1, value2, "ghhy");
            return (Criteria) this;
        }

        public Criteria andGlhIsNull() {
            addCriterion("GLH is null");
            return (Criteria) this;
        }

        public Criteria andGlhIsNotNull() {
            addCriterion("GLH is not null");
            return (Criteria) this;
        }

        public Criteria andGlhEqualTo(BigDecimal value) {
            addCriterion("GLH =", value, "glh");
            return (Criteria) this;
        }

        public Criteria andGlhNotEqualTo(BigDecimal value) {
            addCriterion("GLH <>", value, "glh");
            return (Criteria) this;
        }

        public Criteria andGlhGreaterThan(BigDecimal value) {
            addCriterion("GLH >", value, "glh");
            return (Criteria) this;
        }

        public Criteria andGlhGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GLH >=", value, "glh");
            return (Criteria) this;
        }

        public Criteria andGlhLessThan(BigDecimal value) {
            addCriterion("GLH <", value, "glh");
            return (Criteria) this;
        }

        public Criteria andGlhLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GLH <=", value, "glh");
            return (Criteria) this;
        }

        public Criteria andGlhIn(List<BigDecimal> values) {
            addCriterion("GLH in", values, "glh");
            return (Criteria) this;
        }

        public Criteria andGlhNotIn(List<BigDecimal> values) {
            addCriterion("GLH not in", values, "glh");
            return (Criteria) this;
        }

        public Criteria andGlhBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GLH between", value1, value2, "glh");
            return (Criteria) this;
        }

        public Criteria andGlhNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GLH not between", value1, value2, "glh");
            return (Criteria) this;
        }

        public Criteria andShuijinIsNull() {
            addCriterion("SHUIJIN is null");
            return (Criteria) this;
        }

        public Criteria andShuijinIsNotNull() {
            addCriterion("SHUIJIN is not null");
            return (Criteria) this;
        }

        public Criteria andShuijinEqualTo(BigDecimal value) {
            addCriterion("SHUIJIN =", value, "shuijin");
            return (Criteria) this;
        }

        public Criteria andShuijinNotEqualTo(BigDecimal value) {
            addCriterion("SHUIJIN <>", value, "shuijin");
            return (Criteria) this;
        }

        public Criteria andShuijinGreaterThan(BigDecimal value) {
            addCriterion("SHUIJIN >", value, "shuijin");
            return (Criteria) this;
        }

        public Criteria andShuijinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SHUIJIN >=", value, "shuijin");
            return (Criteria) this;
        }

        public Criteria andShuijinLessThan(BigDecimal value) {
            addCriterion("SHUIJIN <", value, "shuijin");
            return (Criteria) this;
        }

        public Criteria andShuijinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SHUIJIN <=", value, "shuijin");
            return (Criteria) this;
        }

        public Criteria andShuijinIn(List<BigDecimal> values) {
            addCriterion("SHUIJIN in", values, "shuijin");
            return (Criteria) this;
        }

        public Criteria andShuijinNotIn(List<BigDecimal> values) {
            addCriterion("SHUIJIN not in", values, "shuijin");
            return (Criteria) this;
        }

        public Criteria andShuijinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SHUIJIN between", value1, value2, "shuijin");
            return (Criteria) this;
        }

        public Criteria andShuijinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SHUIJIN not between", value1, value2, "shuijin");
            return (Criteria) this;
        }

        public Criteria andQtIsNull() {
            addCriterion("QT is null");
            return (Criteria) this;
        }

        public Criteria andQtIsNotNull() {
            addCriterion("QT is not null");
            return (Criteria) this;
        }

        public Criteria andQtEqualTo(BigDecimal value) {
            addCriterion("QT =", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtNotEqualTo(BigDecimal value) {
            addCriterion("QT <>", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtGreaterThan(BigDecimal value) {
            addCriterion("QT >", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("QT >=", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtLessThan(BigDecimal value) {
            addCriterion("QT <", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("QT <=", value, "qt");
            return (Criteria) this;
        }

        public Criteria andQtIn(List<BigDecimal> values) {
            addCriterion("QT in", values, "qt");
            return (Criteria) this;
        }

        public Criteria andQtNotIn(List<BigDecimal> values) {
            addCriterion("QT not in", values, "qt");
            return (Criteria) this;
        }

        public Criteria andQtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QT between", value1, value2, "qt");
            return (Criteria) this;
        }

        public Criteria andQtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("QT not between", value1, value2, "qt");
            return (Criteria) this;
        }

        public Criteria andLzrhyIsNull() {
            addCriterion("LZRHY is null");
            return (Criteria) this;
        }

        public Criteria andLzrhyIsNotNull() {
            addCriterion("LZRHY is not null");
            return (Criteria) this;
        }

        public Criteria andLzrhyEqualTo(BigDecimal value) {
            addCriterion("LZRHY =", value, "lzrhy");
            return (Criteria) this;
        }

        public Criteria andLzrhyNotEqualTo(BigDecimal value) {
            addCriterion("LZRHY <>", value, "lzrhy");
            return (Criteria) this;
        }

        public Criteria andLzrhyGreaterThan(BigDecimal value) {
            addCriterion("LZRHY >", value, "lzrhy");
            return (Criteria) this;
        }

        public Criteria andLzrhyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LZRHY >=", value, "lzrhy");
            return (Criteria) this;
        }

        public Criteria andLzrhyLessThan(BigDecimal value) {
            addCriterion("LZRHY <", value, "lzrhy");
            return (Criteria) this;
        }

        public Criteria andLzrhyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LZRHY <=", value, "lzrhy");
            return (Criteria) this;
        }

        public Criteria andLzrhyIn(List<BigDecimal> values) {
            addCriterion("LZRHY in", values, "lzrhy");
            return (Criteria) this;
        }

        public Criteria andLzrhyNotIn(List<BigDecimal> values) {
            addCriterion("LZRHY not in", values, "lzrhy");
            return (Criteria) this;
        }

        public Criteria andLzrhyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LZRHY between", value1, value2, "lzrhy");
            return (Criteria) this;
        }

        public Criteria andLzrhyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LZRHY not between", value1, value2, "lzrhy");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 21 17:45:03 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JAVAOAS.T_OUT_JTHY
     *
     * @mbg.generated Wed Jun 21 17:45:03 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}