package com.talkweb.ei.outmanager.model;

public class VOutUserduty extends ImportObj {
	
	
	private String id;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERDUTY.USERID
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERDUTY.NAME
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERDUTY.UNIT
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERDUTY.DUTYID
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    private String dutyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERDUTY.DUTY
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERDUTY.REMARK
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERDUTY.UNITID
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    private String unitid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERDUTY.SELFORG
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    private String selforg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERDUTY.SUBORG
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    private String suborg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERDUTY.USERID
     *
     * @return the value of JAVAOAS.V_OUT_USERDUTY.USERID
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERDUTY.USERID
     *
     * @param userid the value for JAVAOAS.V_OUT_USERDUTY.USERID
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERDUTY.NAME
     *
     * @return the value of JAVAOAS.V_OUT_USERDUTY.NAME
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERDUTY.NAME
     *
     * @param name the value for JAVAOAS.V_OUT_USERDUTY.NAME
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERDUTY.UNIT
     *
     * @return the value of JAVAOAS.V_OUT_USERDUTY.UNIT
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERDUTY.UNIT
     *
     * @param unit the value for JAVAOAS.V_OUT_USERDUTY.UNIT
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERDUTY.DUTYID
     *
     * @return the value of JAVAOAS.V_OUT_USERDUTY.DUTYID
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public String getDutyid() {
        return dutyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERDUTY.DUTYID
     *
     * @param dutyid the value for JAVAOAS.V_OUT_USERDUTY.DUTYID
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public void setDutyid(String dutyid) {
        this.dutyid = dutyid == null ? null : dutyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERDUTY.DUTY
     *
     * @return the value of JAVAOAS.V_OUT_USERDUTY.DUTY
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERDUTY.DUTY
     *
     * @param duty the value for JAVAOAS.V_OUT_USERDUTY.DUTY
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERDUTY.REMARK
     *
     * @return the value of JAVAOAS.V_OUT_USERDUTY.REMARK
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERDUTY.REMARK
     *
     * @param remark the value for JAVAOAS.V_OUT_USERDUTY.REMARK
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERDUTY.UNITID
     *
     * @return the value of JAVAOAS.V_OUT_USERDUTY.UNITID
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public String getUnitid() {
        return unitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERDUTY.UNITID
     *
     * @param unitid the value for JAVAOAS.V_OUT_USERDUTY.UNITID
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public void setUnitid(String unitid) {
        this.unitid = unitid == null ? null : unitid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERDUTY.SELFORG
     *
     * @return the value of JAVAOAS.V_OUT_USERDUTY.SELFORG
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public String getSelforg() {
        return selforg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERDUTY.SELFORG
     *
     * @param selforg the value for JAVAOAS.V_OUT_USERDUTY.SELFORG
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public void setSelforg(String selforg) {
        this.selforg = selforg == null ? null : selforg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERDUTY.SUBORG
     *
     * @return the value of JAVAOAS.V_OUT_USERDUTY.SUBORG
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public String getSuborg() {
        return suborg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERDUTY.SUBORG
     *
     * @param suborg the value for JAVAOAS.V_OUT_USERDUTY.SUBORG
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    public void setSuborg(String suborg) {
        this.suborg = suborg == null ? null : suborg.trim();
    }

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
}