package com.talkweb.ei.outmanager.model;

import java.math.BigDecimal;
import java.util.Date;

public class VOutUsergz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.NAME
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.CODE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.CONCODE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private String concode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.UNIT
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.ID
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.USERID
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.COMPANYID
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private String companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.MONTH
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private String month;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.JIBEN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal jiben;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.JIXIAO
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal jixiao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.GUOJIE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal guojie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.JINTIE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal jintie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.QTGZ
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal qtgz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.JIABAN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal jiaban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.JIANGJIN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal jiangjin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.YFA
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal yfa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.SHIFA
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal shifa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.WUXIAN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal wuxian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.GEREN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal geren;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.SHENGYU
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal shengyu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.YANGLAO
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal yanglao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.YILIAO
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal yiliao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.SHIYE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal shiye;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.GONGJI
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal gongji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.GONGSHANG
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal gongshang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.GSWUXIAN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal gswuxian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.GONGHUI
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal gonghui;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.GUANLI
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal guanli;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.SHUIJIN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal shuijin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.QTJINE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal qtjine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.REMARK
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.STARTFWDATE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private Date startfwdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.STARTBXDATE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private Date startbxdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.SXKK
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal sxkk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JAVAOAS.V_OUT_USERGZ.SHKK
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    private BigDecimal shkk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.NAME
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.NAME
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.NAME
     *
     * @param name the value for JAVAOAS.V_OUT_USERGZ.NAME
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.CODE
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.CODE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.CODE
     *
     * @param code the value for JAVAOAS.V_OUT_USERGZ.CODE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.CONCODE
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.CONCODE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public String getConcode() {
        return concode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.CONCODE
     *
     * @param concode the value for JAVAOAS.V_OUT_USERGZ.CONCODE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setConcode(String concode) {
        this.concode = concode == null ? null : concode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.UNIT
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.UNIT
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.UNIT
     *
     * @param unit the value for JAVAOAS.V_OUT_USERGZ.UNIT
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.ID
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.ID
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.ID
     *
     * @param id the value for JAVAOAS.V_OUT_USERGZ.ID
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.USERID
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.USERID
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.USERID
     *
     * @param userid the value for JAVAOAS.V_OUT_USERGZ.USERID
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.COMPANYID
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.COMPANYID
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public String getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.COMPANYID
     *
     * @param companyid the value for JAVAOAS.V_OUT_USERGZ.COMPANYID
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setCompanyid(String companyid) {
        this.companyid = companyid == null ? null : companyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.MONTH
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.MONTH
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.MONTH
     *
     * @param month the value for JAVAOAS.V_OUT_USERGZ.MONTH
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.JIBEN
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.JIBEN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getJiben() {
        return jiben;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.JIBEN
     *
     * @param jiben the value for JAVAOAS.V_OUT_USERGZ.JIBEN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setJiben(BigDecimal jiben) {
        this.jiben = jiben;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.JIXIAO
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.JIXIAO
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getJixiao() {
        return jixiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.JIXIAO
     *
     * @param jixiao the value for JAVAOAS.V_OUT_USERGZ.JIXIAO
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setJixiao(BigDecimal jixiao) {
        this.jixiao = jixiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.GUOJIE
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.GUOJIE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getGuojie() {
        return guojie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.GUOJIE
     *
     * @param guojie the value for JAVAOAS.V_OUT_USERGZ.GUOJIE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setGuojie(BigDecimal guojie) {
        this.guojie = guojie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.JINTIE
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.JINTIE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getJintie() {
        return jintie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.JINTIE
     *
     * @param jintie the value for JAVAOAS.V_OUT_USERGZ.JINTIE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setJintie(BigDecimal jintie) {
        this.jintie = jintie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.QTGZ
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.QTGZ
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getQtgz() {
        return qtgz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.QTGZ
     *
     * @param qtgz the value for JAVAOAS.V_OUT_USERGZ.QTGZ
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setQtgz(BigDecimal qtgz) {
        this.qtgz = qtgz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.JIABAN
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.JIABAN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getJiaban() {
        return jiaban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.JIABAN
     *
     * @param jiaban the value for JAVAOAS.V_OUT_USERGZ.JIABAN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setJiaban(BigDecimal jiaban) {
        this.jiaban = jiaban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.JIANGJIN
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.JIANGJIN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getJiangjin() {
        return jiangjin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.JIANGJIN
     *
     * @param jiangjin the value for JAVAOAS.V_OUT_USERGZ.JIANGJIN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setJiangjin(BigDecimal jiangjin) {
        this.jiangjin = jiangjin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.YFA
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.YFA
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getYfa() {
        return yfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.YFA
     *
     * @param yfa the value for JAVAOAS.V_OUT_USERGZ.YFA
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setYfa(BigDecimal yfa) {
        this.yfa = yfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.SHIFA
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.SHIFA
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getShifa() {
        return shifa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.SHIFA
     *
     * @param shifa the value for JAVAOAS.V_OUT_USERGZ.SHIFA
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setShifa(BigDecimal shifa) {
        this.shifa = shifa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.WUXIAN
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.WUXIAN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getWuxian() {
        return wuxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.WUXIAN
     *
     * @param wuxian the value for JAVAOAS.V_OUT_USERGZ.WUXIAN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setWuxian(BigDecimal wuxian) {
        this.wuxian = wuxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.GEREN
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.GEREN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getGeren() {
        return geren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.GEREN
     *
     * @param geren the value for JAVAOAS.V_OUT_USERGZ.GEREN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setGeren(BigDecimal geren) {
        this.geren = geren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.SHENGYU
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.SHENGYU
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getShengyu() {
        return shengyu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.SHENGYU
     *
     * @param shengyu the value for JAVAOAS.V_OUT_USERGZ.SHENGYU
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setShengyu(BigDecimal shengyu) {
        this.shengyu = shengyu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.YANGLAO
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.YANGLAO
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getYanglao() {
        return yanglao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.YANGLAO
     *
     * @param yanglao the value for JAVAOAS.V_OUT_USERGZ.YANGLAO
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setYanglao(BigDecimal yanglao) {
        this.yanglao = yanglao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.YILIAO
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.YILIAO
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getYiliao() {
        return yiliao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.YILIAO
     *
     * @param yiliao the value for JAVAOAS.V_OUT_USERGZ.YILIAO
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setYiliao(BigDecimal yiliao) {
        this.yiliao = yiliao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.SHIYE
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.SHIYE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getShiye() {
        return shiye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.SHIYE
     *
     * @param shiye the value for JAVAOAS.V_OUT_USERGZ.SHIYE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setShiye(BigDecimal shiye) {
        this.shiye = shiye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.GONGJI
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.GONGJI
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getGongji() {
        return gongji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.GONGJI
     *
     * @param gongji the value for JAVAOAS.V_OUT_USERGZ.GONGJI
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setGongji(BigDecimal gongji) {
        this.gongji = gongji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.GONGSHANG
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.GONGSHANG
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getGongshang() {
        return gongshang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.GONGSHANG
     *
     * @param gongshang the value for JAVAOAS.V_OUT_USERGZ.GONGSHANG
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setGongshang(BigDecimal gongshang) {
        this.gongshang = gongshang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.GSWUXIAN
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.GSWUXIAN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getGswuxian() {
        return gswuxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.GSWUXIAN
     *
     * @param gswuxian the value for JAVAOAS.V_OUT_USERGZ.GSWUXIAN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setGswuxian(BigDecimal gswuxian) {
        this.gswuxian = gswuxian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.GONGHUI
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.GONGHUI
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getGonghui() {
        return gonghui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.GONGHUI
     *
     * @param gonghui the value for JAVAOAS.V_OUT_USERGZ.GONGHUI
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setGonghui(BigDecimal gonghui) {
        this.gonghui = gonghui;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.GUANLI
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.GUANLI
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getGuanli() {
        return guanli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.GUANLI
     *
     * @param guanli the value for JAVAOAS.V_OUT_USERGZ.GUANLI
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setGuanli(BigDecimal guanli) {
        this.guanli = guanli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.SHUIJIN
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.SHUIJIN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getShuijin() {
        return shuijin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.SHUIJIN
     *
     * @param shuijin the value for JAVAOAS.V_OUT_USERGZ.SHUIJIN
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setShuijin(BigDecimal shuijin) {
        this.shuijin = shuijin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.QTJINE
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.QTJINE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getQtjine() {
        return qtjine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.QTJINE
     *
     * @param qtjine the value for JAVAOAS.V_OUT_USERGZ.QTJINE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setQtjine(BigDecimal qtjine) {
        this.qtjine = qtjine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.REMARK
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.REMARK
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.REMARK
     *
     * @param remark the value for JAVAOAS.V_OUT_USERGZ.REMARK
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.STARTFWDATE
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.STARTFWDATE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public Date getStartfwdate() {
        return startfwdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.STARTFWDATE
     *
     * @param startfwdate the value for JAVAOAS.V_OUT_USERGZ.STARTFWDATE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setStartfwdate(Date startfwdate) {
        this.startfwdate = startfwdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.STARTBXDATE
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.STARTBXDATE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public Date getStartbxdate() {
        return startbxdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.STARTBXDATE
     *
     * @param startbxdate the value for JAVAOAS.V_OUT_USERGZ.STARTBXDATE
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setStartbxdate(Date startbxdate) {
        this.startbxdate = startbxdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.SXKK
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.SXKK
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getSxkk() {
        return sxkk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.SXKK
     *
     * @param sxkk the value for JAVAOAS.V_OUT_USERGZ.SXKK
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setSxkk(BigDecimal sxkk) {
        this.sxkk = sxkk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JAVAOAS.V_OUT_USERGZ.SHKK
     *
     * @return the value of JAVAOAS.V_OUT_USERGZ.SHKK
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public BigDecimal getShkk() {
        return shkk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JAVAOAS.V_OUT_USERGZ.SHKK
     *
     * @param shkk the value for JAVAOAS.V_OUT_USERGZ.SHKK
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    public void setShkk(BigDecimal shkk) {
        this.shkk = shkk;
    }
}