package com.talkweb.ei.outmanager.dao;

import com.talkweb.ei.outmanager.model.OutCompany;
import com.talkweb.ei.outmanager.model.OutCompanyExample;
import com.talkweb.ei.outmanager.model.OutContract;
import com.talkweb.ei.outmanager.model.OutContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    long countByExample(OutContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    int deleteByExample(OutContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    int insert(OutContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    int insertSelective(OutContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    List<OutContract> selectByExample(OutContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    OutContract selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    int updateByExampleSelective(@Param("record") OutContract record, @Param("example") OutContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    int updateByExample(@Param("record") OutContract record, @Param("example") OutContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    int updateByPrimaryKeySelective(OutContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_CONTRACT
     *
     * @mbg.generated Mon May 01 15:21:12 CST 2017
     */
    int updateByPrimaryKey(OutContract record);
    
    
    
    //∑÷“≥≤È—Ø
    List<OutContract> selectPageByExample(OutContractExample example);
}