package com.talkweb.ei.outmanager.dao;

import com.talkweb.ei.outmanager.model.OutContract;
import com.talkweb.ei.outmanager.model.OutContractExample;
import com.talkweb.ei.outmanager.model.OutUser;
import com.talkweb.ei.outmanager.model.OutUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER
     *
     * @mbg.generated Thu May 18 11:20:05 CST 2017
     */
    long countByExample(OutUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER
     *
     * @mbg.generated Thu May 18 11:20:05 CST 2017
     */
    int deleteByExample(OutUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER
     *
     * @mbg.generated Thu May 18 11:20:05 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER
     *
     * @mbg.generated Thu May 18 11:20:05 CST 2017
     */
    int insert(OutUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER
     *
     * @mbg.generated Thu May 18 11:20:05 CST 2017
     */
    int insertSelective(OutUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER
     *
     * @mbg.generated Thu May 18 11:20:05 CST 2017
     */
    List<OutUser> selectByExample(OutUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER
     *
     * @mbg.generated Thu May 18 11:20:05 CST 2017
     */
    OutUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER
     *
     * @mbg.generated Thu May 18 11:20:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") OutUser record, @Param("example") OutUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER
     *
     * @mbg.generated Thu May 18 11:20:05 CST 2017
     */
    int updateByExample(@Param("record") OutUser record, @Param("example") OutUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER
     *
     * @mbg.generated Thu May 18 11:20:05 CST 2017
     */
    int updateByPrimaryKeySelective(OutUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER
     *
     * @mbg.generated Thu May 18 11:20:05 CST 2017
     */
    int updateByPrimaryKey(OutUser record);
    
    
    //∑÷“≥≤È—Ø
    List<OutUser> selectPageByExample(OutUserExample example);
}