package com.talkweb.ei.outmanager.dao;

import com.talkweb.ei.outmanager.model.TOutUserZyinfo;
import com.talkweb.ei.outmanager.model.TOutUserZyinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOutUserZyinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_ZYINFO
     *
     * @mbg.generated Wed May 24 16:25:59 CST 2017
     */
    long countByExample(TOutUserZyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_ZYINFO
     *
     * @mbg.generated Wed May 24 16:25:59 CST 2017
     */
    int deleteByExample(TOutUserZyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_ZYINFO
     *
     * @mbg.generated Wed May 24 16:25:59 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_ZYINFO
     *
     * @mbg.generated Wed May 24 16:25:59 CST 2017
     */
    int insert(TOutUserZyinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_ZYINFO
     *
     * @mbg.generated Wed May 24 16:25:59 CST 2017
     */
    int insertSelective(TOutUserZyinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_ZYINFO
     *
     * @mbg.generated Wed May 24 16:25:59 CST 2017
     */
    List<TOutUserZyinfo> selectByExample(TOutUserZyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_ZYINFO
     *
     * @mbg.generated Wed May 24 16:25:59 CST 2017
     */
    TOutUserZyinfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_ZYINFO
     *
     * @mbg.generated Wed May 24 16:25:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") TOutUserZyinfo record, @Param("example") TOutUserZyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_ZYINFO
     *
     * @mbg.generated Wed May 24 16:25:59 CST 2017
     */
    int updateByExample(@Param("record") TOutUserZyinfo record, @Param("example") TOutUserZyinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_ZYINFO
     *
     * @mbg.generated Wed May 24 16:25:59 CST 2017
     */
    int updateByPrimaryKeySelective(TOutUserZyinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_USER_ZYINFO
     *
     * @mbg.generated Wed May 24 16:25:59 CST 2017
     */
    int updateByPrimaryKey(TOutUserZyinfo record);
}