package com.talkweb.ei.outmanager.dao;

import com.talkweb.ei.outmanager.model.TOutReport;
import com.talkweb.ei.outmanager.model.TOutReportExample;
import com.talkweb.ei.outmanager.model.TOutReportst;
import com.talkweb.ei.outmanager.model.TOutReportstExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOutReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_REPORT
     *
     * @mbg.generated Tue Jul 18 11:12:00 CST 2017
     */
    long countByExample(TOutReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_REPORT
     *
     * @mbg.generated Tue Jul 18 11:12:01 CST 2017
     */
    int deleteByExample(TOutReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_REPORT
     *
     * @mbg.generated Tue Jul 18 11:12:01 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_REPORT
     *
     * @mbg.generated Tue Jul 18 11:12:01 CST 2017
     */
    int insert(TOutReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_REPORT
     *
     * @mbg.generated Tue Jul 18 11:12:01 CST 2017
     */
    int insertSelective(TOutReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_REPORT
     *
     * @mbg.generated Tue Jul 18 11:12:01 CST 2017
     */
    List<TOutReport> selectByExample(TOutReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_REPORT
     *
     * @mbg.generated Tue Jul 18 11:12:01 CST 2017
     */
    TOutReport selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_REPORT
     *
     * @mbg.generated Tue Jul 18 11:12:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") TOutReport record, @Param("example") TOutReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_REPORT
     *
     * @mbg.generated Tue Jul 18 11:12:01 CST 2017
     */
    int updateByExample(@Param("record") TOutReport record, @Param("example") TOutReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_REPORT
     *
     * @mbg.generated Tue Jul 18 11:12:01 CST 2017
     */
    int updateByPrimaryKeySelective(TOutReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_REPORT
     *
     * @mbg.generated Tue Jul 18 11:12:01 CST 2017
     */
    int updateByPrimaryKey(TOutReport record);
    
    
    
    //∑÷“≥≤È—Ø
    List<TOutReport> selectPageByExample(TOutReportExample example);    
    
    
    
}