package com.talkweb.ei.outmanager.dao;

import com.talkweb.ei.outmanager.model.TOutDict;
import com.talkweb.ei.outmanager.model.TOutDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOutDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DICT
     *
     * @mbg.generated Mon May 22 09:48:34 CST 2017
     */
    long countByExample(TOutDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DICT
     *
     * @mbg.generated Mon May 22 09:48:34 CST 2017
     */
    int deleteByExample(TOutDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DICT
     *
     * @mbg.generated Mon May 22 09:48:34 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DICT
     *
     * @mbg.generated Mon May 22 09:48:34 CST 2017
     */
    int insert(TOutDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DICT
     *
     * @mbg.generated Mon May 22 09:48:34 CST 2017
     */
    int insertSelective(TOutDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DICT
     *
     * @mbg.generated Mon May 22 09:48:34 CST 2017
     */
    List<TOutDict> selectByExample(TOutDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DICT
     *
     * @mbg.generated Mon May 22 09:48:34 CST 2017
     */
    TOutDict selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DICT
     *
     * @mbg.generated Mon May 22 09:48:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") TOutDict record, @Param("example") TOutDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DICT
     *
     * @mbg.generated Mon May 22 09:48:34 CST 2017
     */
    int updateByExample(@Param("record") TOutDict record, @Param("example") TOutDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DICT
     *
     * @mbg.generated Mon May 22 09:48:34 CST 2017
     */
    int updateByPrimaryKeySelective(TOutDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DICT
     *
     * @mbg.generated Mon May 22 09:48:34 CST 2017
     */
    int updateByPrimaryKey(TOutDict record);
}