package com.talkweb.ei.outmanager.dao;

import com.talkweb.ei.outmanager.model.TOutDutymaping;
import com.talkweb.ei.outmanager.model.TOutDutymapingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TOutDutymapingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DUTYMAPING
     *
     * @mbg.generated Fri Jun 30 15:22:43 CST 2017
     */
    long countByExample(TOutDutymapingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DUTYMAPING
     *
     * @mbg.generated Fri Jun 30 15:22:43 CST 2017
     */
    int deleteByExample(TOutDutymapingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DUTYMAPING
     *
     * @mbg.generated Fri Jun 30 15:22:43 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DUTYMAPING
     *
     * @mbg.generated Fri Jun 30 15:22:43 CST 2017
     */
    int insert(TOutDutymaping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DUTYMAPING
     *
     * @mbg.generated Fri Jun 30 15:22:43 CST 2017
     */
    int insertSelective(TOutDutymaping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DUTYMAPING
     *
     * @mbg.generated Fri Jun 30 15:22:43 CST 2017
     */
    List<TOutDutymaping> selectByExample(TOutDutymapingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DUTYMAPING
     *
     * @mbg.generated Fri Jun 30 15:22:43 CST 2017
     */
    TOutDutymaping selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DUTYMAPING
     *
     * @mbg.generated Fri Jun 30 15:22:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") TOutDutymaping record, @Param("example") TOutDutymapingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DUTYMAPING
     *
     * @mbg.generated Fri Jun 30 15:22:43 CST 2017
     */
    int updateByExample(@Param("record") TOutDutymaping record, @Param("example") TOutDutymapingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DUTYMAPING
     *
     * @mbg.generated Fri Jun 30 15:22:43 CST 2017
     */
    int updateByPrimaryKeySelective(TOutDutymaping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.T_OUT_DUTYMAPING
     *
     * @mbg.generated Fri Jun 30 15:22:43 CST 2017
     */
    int updateByPrimaryKey(TOutDutymaping record);
}