package com.talkweb.ei.outmanager.dao;

import com.talkweb.ei.outmanager.model.VOutUserduty;
import com.talkweb.ei.outmanager.model.VOutUserdutyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VOutUserdutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERDUTY
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    long countByExample(VOutUserdutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERDUTY
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    int deleteByExample(VOutUserdutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERDUTY
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    int insert(VOutUserduty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERDUTY
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    int insertSelective(VOutUserduty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERDUTY
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    List<VOutUserduty> selectByExample(VOutUserdutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERDUTY
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") VOutUserduty record, @Param("example") VOutUserdutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERDUTY
     *
     * @mbg.generated Fri Jun 30 16:57:05 CST 2017
     */
    int updateByExample(@Param("record") VOutUserduty record, @Param("example") VOutUserdutyExample example);
    
    
    
    
    //∑÷“≥≤È—Ø
    List<VOutUserduty> selectPageByExample(VOutUserdutyExample example);
    
    
    
    
}