package com.talkweb.ei.outmanager.dao;

import com.talkweb.ei.outmanager.model.OutUser;
import com.talkweb.ei.outmanager.model.OutUserExample;
import com.talkweb.ei.outmanager.model.VOutUsergz;
import com.talkweb.ei.outmanager.model.VOutUsergzExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VOutUsergzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERGZ
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    long countByExample(VOutUsergzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERGZ
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    int deleteByExample(VOutUsergzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERGZ
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    int insert(VOutUsergz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERGZ
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    int insertSelective(VOutUsergz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERGZ
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    List<VOutUsergz> selectByExample(VOutUsergzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERGZ
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") VOutUsergz record, @Param("example") VOutUsergzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JAVAOAS.V_OUT_USERGZ
     *
     * @mbg.generated Mon Jun 05 17:31:36 CST 2017
     */
    int updateByExample(@Param("record") VOutUsergz record, @Param("example") VOutUsergzExample example);
    
    
    
    //∑÷“≥≤È—Ø
    List<VOutUsergz> selectPageByExample(VOutUsergzExample example);
    
    
}